---
title: "Shorebirds"
format: revealjs
scrollable: true
---

# Shorebirds

-   シギチドリ
-   春は生殖羽のきれいなのが一瞬で渡っていく
-   秋は非生殖羽の成鳥が渡った後、幼鳥がずるずる渡っていくイメージ
 
## Shorebirds in Miyagi

宮城で観察したことのあるシギチ

## Stilits and Avocets

-   セイタカシギ
-   ソリハシセイタカシギ

## セイタカシギ

-   本州でも繁殖する個体がいるらしい。宮城でも近年観察記録が増えてきた。
-   Stiltは竹馬という意味。
-   どっこいしょと座っているところを見てみたい。
-   くちばしの先端を水面につけて、首を左右に振る採餌方法をとる。面白バードのヘラサギと同じやり方。

## ソリハシセイタカシギ

-   稀な旅鳥。県内では11月から正月など、わけのわからないタイミングで観察されていたりする印象。
-   モノクロの複雑な模様の中に淡いブルーが入っていて、スポーツ少年のシューズみたいな配色だと思う

## Plovers and Lapwings

-   タゲリ
-   ケリ
-   ムナグロ
-   ダイゼン
-   ハジロコチドリ
-   イカルチドリ
-   コチドリ
-   シロチドリ
-   メダイチドリ

## タゲリ

-   ウミネコよりも猫みたいな鳴き声で鳴く。
-   翼のエメラルドは構造色なので、陽の光を反射するとキラキラ輝いて見える。
-   体のわりに大きな丸い翼でひらひら飛ぶ。
-   冬の貴婦人と呼ばれる。Dame d'hiver

## ケリ

-   県内では少数が夏にいる。見る機会は少ない
-   北陸とか近畿のほうに行くとわんさかいるのでビビる

## ムナグロ

-   種小名fluvaは「雨」の意味。
-   ダイゼンより一回り小さく、腹部に広がる黄金色の横斑が特徴
-   淡水環境にも海水環境の干潟にも来る。
-   生殖羽のオスは真っ黒

## ダイゼン

-   ムナグロよりぼってりしている。宮城ではムナグロよりも少ない印象
-   関東や九州の干潟では越冬しているので、いるところにいけばいる
-   ムナグロが黄金色なら、ダイゼンは銀白色の横斑
-   「大膳」なのでめちゃうまいらしい？

## ハジロコチドリ

-   稀な旅鳥。
-   2024年8月6日に生殖羽の本種を発見。
-   くちばしの付け根が黄色く先端が黒いので、小さいハクチョウみたい（そうでもない）

## イカルチドリ

-   冬鳥。
-   よく見るとコチドリより大きい。
-   よく見るとコチドリよりくちばしが長い

## コチドリ

-   種小名dubiusは「あいまいな」の意味。
-   ぱっちりアイリングの夏鳥

## シロチドリ

-   日本で繁殖するシギチの一種。
-   砂浜で繁殖する。シロチドリに優しくありたい

## メダイチドリ

-   橙色だけど、「目大千鳥」。黒い模様が巨大な目に見えるらしい？
-   非生殖羽はコチドリやシロチドリ、イカルチドリなどと似ている
-   初心者なので、まだオオメダイを県内で観察したことがない。

## Curlews

-   チュウシャクシギ
-   コシャクシギ
-   ホウロクシギ
-   ダイシャクシギ

## チュウシャクシギ

-   個体数が多いので観察頻度が多い。
-   シーズン所見だとくちばしが長く見えるが、慣れてくるとそんなことはない。
-   くちばしの長さと湾曲が特徴的だが、幼鳥は短めらしい。見てみたい。
-   海岸でよく見かける印象だが、農耕地や田畑にも入る。

## コシャクシギ

-   少ない旅鳥。年変動がある。
-   宮城では2022年の当たり年に見た限り。
-   チュウシャクシギよりも淡いクリーム色の羽毛で、一回り以上小さかった。
-   農耕地で発見した。

## ホウロクシギ

-   なぜか種小名がmadagascariensisだが、別にマダガスカルにはいない
-   ダイシャクシギと似るが、下尾筒や腹、腰が褐色を帯びていることで識別可能。
-   干潟の泥の上を歩くが、ハヤブサにびっくりして海水に浸かってしまったホウロクシギを一度だけ見たことがある。

## ダイシャクシギ

-   ホウロクシギより全体的に白い。
-   採餌の時、くちばしを土に入れるために顔を下げるので、下尾筒の色が確認しやすい。

## Godwits

-   オオソリハシシギ
-   オグロシギ

## オオソリハシシギ

-   4月下旬に見られる生殖羽は赤褐色。
-   くちばしが少し上に反っている。
-   Bar-tailedの英名の通り、尾羽は褐色の横斑が入る。オグロシギとの識別ポイント

## オグロシギ

-   秋に沼で一度だけ観察したのみ。
-   Black-tailedの英名の通り、尾羽は真っ黒。オオソリハシシギとの識別ポイント

## Turnstone

-   キョウジョシギ

## キョウジョシギ

-   京女鴫。鮮やかではんなりした模様。
-   農耕地にもいるが、よく見るのはごつごつした海岸や岩礁。
-   テトラポッドの上に集団で集まって、波が来るたびパタパタ飛んで移動しながら採餌している。
-   turnstoneの通り、石をひっくり返して裏にくっつく虫を食べる行動をするらしい。見てみたい。

## Sandpipers

-   オバシギ
-   コオバシギ
-   エリマキシギ
-   キリアイ
-   ウズラシギ
-   オジロトウネン
-   ヒバリシギ
-   トウネン
-   ミユビシギ
-   ハマシギ

## Dowitchers

-   オオハシシギ

## Woodcocks and Snipes

-   タシギ

## Sandpiper (Xenus)

-   ソリハシシギ

## Phalaropes

-   アカエリヒレアシシギ

## Sandpipers (Actitis)

-   イソシギ

## Sandpipers (Tringa)

-   クサシギ
-   キアシシギ
-   アカアシシギ
-   コアオアシシギ
-   タカブシギ
-   ツルシギ
-   アオアシシギ

## 見たいやつ

-   ミヤコドリ
-   オオメダイチドリ
-   タマシギ
-   レンカク
-   サルハマシギ
-   ヘラシギ
-   メリケンキアシシギ
-   ツバメチドリ