---
title: "太平洋フェリー（名古屋↔仙台↔苫小牧）"
format: html
---

### 2021.03.11 仙台→苫小牧

初めての仙苫。航路大好き友人に連れられて三人で北海道遠征をすることになった。

仙台からは19:40発になるため、17:00頃にターミナルに到着し、スーパーで買った惣菜などの夜ご飯を2m離れて食べたり、見られそうな鳥や見たい鳥を2m離れて談義するなどして過ごした。コロナパンデミックから1年後だったので、ソーシャルディスタンスしていた。

19:30には乗船を済ませ、翌朝から始まる航路探鳥の舞台である甲板を下見した。冷たい夜風と共に体に付着した潮を落とすため、混雑前に大浴場に入った。太平洋フェリーは大浴場付きなのだ。うれしい

日の出と共に航路探鳥を始めるため寝台に駆け込んだ。同室には一般の方も利用されていたので、目覚ましの音は最小限に控えた。航路探鳥はまだ2回目。どんな鳥と出会えるか、さながらキジバトの求愛ダンスみてーに胸を膨らませながら床に就いた。

翌朝は5:00くらいから観察を始めた。太平洋の波をかき分け征くフェリーの重低音が覚醒の助けになってくれていた。朝のルーティンをしっかりこなして甲板に陣取る。まだ日も出ていなかったように記憶しているが、ミツユビカモメ（学名もtridactyla）がたくさん飛んでいて楽しい。遠くを滑翔するコアホウドリの大きさに驚いたり、船体付近に現れたウミガラスsp.などに発狂したり、今まで航路以外で見る機会がなかった海鳥を見ることが出来て嬉しかった。

左舷で観察すると本州沿岸沿いをハクチョウ・ガンの群れが並走しているのが見えた。更に甲板での観察中、上空をマガンとシジュウカラガンの群れが追い抜いていった。青空を背景にこれからシベリアやカムチャツカに向かうのだろう。航路経験が少なく、海鳥を見るものだと思っていたがこのように渡りを観察できるチャンスでもある事を知った。なるべく船首の方で観察していたがそれでもコンスタントに風が吹き付けるので、手袋貫通して霜焼けになる。太平洋フェリーのあつあつお茶サーバーを利用して休憩しながら苫小牧港まで楽しんだ。

### 2021.03.16 苫小牧→仙台

北海道遠征の最終日。岩手沖からの観察。旅愁に浸る間もないほど海鳥が多かった。3.11の往路では観察できなかったオオミズナギドリ、クロアシアホウドリ、ウトウ、ウミスズメなどのほか、ウミガラスsp.の数も多く楽しめた。

ウトウがめちゃくちゃに多かったが、足島（2020年、コシジロウミツバメのヒナが見つかっている。今まで岩手県三貫島が繁殖南限だと考えられていたが、その記録を更新）での繁殖に向けて集まってきていたのだろうか。

### 2022.08.25　苫小牧→仙台

函館から苫小牧まで一人旅をした帰り。ちなみに函館まではシンプルに新幹線で行った。

オオミズナギドリがめちゃくちゃ飛んだ。水面付近をアカエリヒレアシシギが飛んでいた。あと同世代くらいの鳥屋にあった。めちゃくちゃな虚無だったけど航路自体が好きなのでまぁOKという感じ。トビウオ眺めてた。

### 2023.09.20, 09.21　仙台→名古屋

就活終わって漸く時間が出来たので、シンプル旅行で名古屋に行ってみた。

名古屋行きのフェリーは12:50発なので、苫小牧行きと違って昼前から移動しなければならない。寝室を確認して早速甲板で待機。いわき沖までアカエリヒレアシシギがちょろちょろ出たくらいだったが、いわき沖はオオミズナギドリ、ウミネコの巨大な塊が見えて面白かった。まだ鳥山が見えていたが日も暮れてきたので、17:50に観察を終了した。

翌日は5:30から観察を開始。静岡県御前崎沖から。三河あたりが鳥の密度が高く、コンスタントにオオミズナギドリやウミネコが飛んでいた。伊良湖崎あたりでタカ見えないかなぁと、頑張って8倍双眼鏡で曇天を凝視したが、トビっぽいシルエットが飛んでいることしか分からなかった。あり得ないくらい高所をクロアシアホウドリが1羽だけ旋回していた。種数は稼げなかったが（時期が微妙すぎる...）、初めて乗った航路だったので楽しめた。

### 2023.09.25　名古屋→仙台

5:30、鴨川沖からスタート。オオミズナギドリたくさん、ウミネコ、オオセグロカモメ、ウミウ、以上。アカエリヒレアシシギも見られなくなって虚無さが増した。相変わらずいわき沖は賑やかだった。16:30の仙台港着時はどっと疲れた。

### 2024.03.30　名古屋→仙台

帰りだけフェリーを利用した。5:30、房総半島沖からスタート。

半年前にも乗っていたが、今回は海鳥が多かった。やっぱり時期の問題が大きそう。

クロガモ、アカエリカイツブリ、カンムリカイツブリ、ハジロカイツブリなどが界面に浮いていた。またアホウドリも成幼合わせて9羽ほど観察できた。クロアシアホウドリやコアホウドリもいた。ヒメウがいたのには驚いた。東北以北のイメージが強いが、関東辺りにもいるのは知らなかった。あとハクセキレイが飛んでいた。仙台着は15:30

### 2024.09.21　仙台→苫小牧

八戸↔苫小牧のフェリーに乗るために、一度苫小牧までフェリーで行くことにした。9月の三連休は、2023年の仙台↔名古屋につづき二度目の航路。

今回はポツポツと小雨が降る中のスタート。ハジロミズナギドリが暗いうちから40羽ほど登場。昨年同時期に仙台↔名古屋を行ったが、海域の違いなのか、仙名航路では見られなかった。Pterodroma属は海鳥ハンドなどで見る限り、他のミズナギドリの中で顔が可愛い感じがする。たぶん瞼がかさになっていて、目元が大きく見えるからだろう。黒白のコントラストがはっきりしていてキャッチーなのもあるかもしれない。吻が寸詰まりで面長な印象がないからかもしれない。曇天の中、一定の頻度の羽ばたきを繰り返しつつも体がブレない飛び方をしており、プロペラのおもちゃみたいだと感じた。

入港・出港時は甲板に人が出てくる時間。苫小牧港入港時も遠く砂浜にわちゃわちゃしているシギチを識別していると甲板に人が集まってきて、入港の様子を撮影したり眺めたりしていた。ちなみにシギチはムナグロとオオソリハシシギだった。識別を終了した辺りで苫小牧港の堤防が現れた。念のため変なカモメが入っていないか観察することにした。

船の動きに身を任せ、双眼鏡には次から次へ新しいカモメが映る。ほとんどがウミネコとオオセグロカモメだったが、急に１羽、真っ黒なカモメが入ってきた。よく見るとミヤコドリだ！東北ではまず見られない鳥で、2023年始に福岡の干潟で見て以来だった。驚いて小さく叫んでしまった...急いで撮影して観察を続けた。こういうことがあるから航路は楽しいよな～となった。

### 2024.09.24　苫小牧→仙台

5:30頃から観察開始。苫仙は2021年3月以来当てていないのであまり期待しないでいた。6:00頃、船尾の方から口笛のような音が聞こえる。凪いでいたとはいえフェリーの駆動音に負けずに船首まで聞こえてくる。相当大きな声で口笛でも吹いているのかしら、と思ったが、上空を１羽のチュウシャクシギが追い越していくのを見て何が起こっていたのかを理解した。

識別出来なかったがヒレアシシギ類が40、コアホウドリ7、クロアシアホウドリ3といった感じ。コアホウは数個体が船の近くを並走してくれた。