---
title: "航路探鳥"
format: html
---

## 苫小牧↔仙台↔名古屋（太平洋フェリー）

### 2021.03.11 仙台→苫小牧

初めての仙苫。航路大好き友人に連れられて三人で北海道遠征をすることになった。

仙台からは19:40発になるため、17:00頃にターミナルに到着し、スーパーで買った惣菜などの夜ご飯を2m離れて食べたり、見られそうな鳥や見たい鳥を2m離れて談義するなどして過ごした。コロナパンデミックから1年後だったので、ソーシャルディスタンスしていた。

19:30には乗船を済ませ、翌朝から始まる航路探鳥の舞台である甲板を下見した。冷たい夜風と共に体に付着した潮を落とすため、混雑前に大浴場に入った。太平洋フェリーは大浴場付きなのだ。うれしい

日の出と共に航路探鳥を始めるため寝台に駆け込んだ。同室には一般の方も利用されていたので、目覚ましの音は最小限に控えた。航路探鳥はまだ2回目。どんな鳥と出会えるか、さながらキジバトの求愛ダンスみてーに胸を膨らませながら床に就いた。

翌朝は5:00くらいから観察を始めた。太平洋の波をかき分け征くフェリーの重低音が覚醒の助けになってくれていた。朝のルーティンをしっかりこなして甲板に陣取る。まだ日も出ていなかったように記憶しているが、ミツユビカモメ（学名もtridactyla）がたくさん飛んでいて楽しい。遠くを滑翔するコアホウドリの大きさに驚いたり、船体付近に現れたウミガラスsp.などに発狂したり、今まで航路以外で見る機会がなかった海鳥を見ることが出来て嬉しかった。

左舷で観察すると本州沿岸沿いをハクチョウ・ガンの群れが並走しているのが見えた。更に甲板での観察中、上空をマガンとシジュウカラガンの群れが追い抜いていった。青空を背景にこれからシベリアやカムチャツカに向かうのだろう。航路経験が少なく、海鳥を見るものだと思っていたがこのように渡りを観察できるチャンスでもある事を知った。なるべく船首の方で観察していたがそれでもコンスタントに風が吹き付けるので、手袋貫通して霜焼けになる。太平洋フェリーのあつあつお茶サーバーを利用して休憩しながら苫小牧港まで楽しんだ。

### 2021.03.16 苫小牧→仙台

北海道遠征の最終日。岩手沖からの観察。旅愁に浸る間もないほど海鳥が多かった。3.11の往路では観察できなかったオオミズナギドリ、クロアシアホウドリ、ウトウ、ウミスズメなどのほか、ウミガラスsp.の数も多く楽しめた。

ウトウがめちゃくちゃに多かったが、足島（2020年、コシジロウミツバメのヒナが見つかっている。今まで岩手県三貫島が繁殖南限だと考えられていたが、その記録を更新）での繁殖に向けて集まってきていたのだろうか。

### 2022.08.25　苫小牧→仙台

函館から苫小牧まで一人旅をした帰り。ちなみに函館まではシンプルに新幹線で行った。

オオミズナギドリがめちゃくちゃ飛んだ。水面付近をアカエリヒレアシシギが飛んでいた。あと同世代くらいの鳥屋にあった。めちゃくちゃな虚無だったけど航路自体が好きなのでまぁOKという感じ。トビウオ眺めてた。

### 2023.09.20, 09.21　仙台→名古屋

就活終わって漸く時間が出来たので、シンプル旅行で名古屋に行ってみた。

名古屋行きのフェリーは12:50発なので、苫小牧行きと違って昼前から移動しなければならない。寝室を確認して早速甲板で待機。いわき沖までアカエリヒレアシシギがちょろちょろ出たくらいだったが、いわき沖はオオミズナギドリ、ウミネコの巨大な塊が見えて面白かった。まだ鳥山が見えていたが日も暮れてきたので、17:50に観察を終了した。

翌日は5:30から観察を開始。静岡県御前崎沖から。三河あたりが鳥の密度が高く、コンスタントにオオミズナギドリやウミネコが飛んでいた。伊良湖崎あたりでタカ見えないかなぁと、頑張って8倍双眼鏡で曇天を凝視したが、トビっぽいシルエットが飛んでいることしか分からなかった。あり得ないくらい高所をクロアシアホウドリが1羽だけ旋回していた。種数は稼げなかったが（時期が微妙すぎる...）、初めて乗った航路だったので楽しめた。

### 2023.09.25　名古屋→仙台

5:30、鴨川沖からスタート。オオミズナギドリたくさん、ウミネコ、オオセグロカモメ、ウミウ、以上。アカエリヒレアシシギも見られなくなって虚無さが増した。相変わらずいわき沖は賑やかだった。16:30の仙台港着時はどっと疲れた。

### 2024.03.30　名古屋→仙台

帰りだけフェリーを利用した。5:30、房総半島沖からスタート。

半年前にも乗っていたが、今回は海鳥が多かった。やっぱり時期の問題が大きそう。

クロガモ、アカエリカイツブリ、カンムリカイツブリ、ハジロカイツブリなどが界面に浮いていた。またアホウドリも成幼合わせて9羽ほど観察できた。クロアシアホウドリやコアホウドリもいた。ヒメウがいたのには驚いた。東北以北のイメージが強いが、関東辺りにもいるのは知らなかった。あとハクセキレイが飛んでいた。仙台着は15:30

### 2024.09.21　仙台→苫小牧

八戸↔苫小牧のフェリーに乗るために、一度苫小牧までフェリーで行くことにした。9月の三連休は、2023年の仙台↔名古屋につづき二度目の航路。

今回はポツポツと小雨が降る中のスタート。ハジロミズナギドリが暗いうちから40羽ほど登場。昨年同時期に仙台↔名古屋を行ったが、海域の違いなのか、仙名航路では見られなかった。Pterodroma属は海鳥ハンドなどで見る限り、他のミズナギドリの中で顔が可愛い感じがする。たぶん瞼がかさになっていて、目元が大きく見えるからだろう。黒白のコントラストがはっきりしていてキャッチーなのもあるかもしれない。吻が寸詰まりで面長な印象がないからかもしれない。曇天の中、一定の頻度の羽ばたきを繰り返しつつも体がブレない飛び方をしており、プロペラのおもちゃみたいだと感じた。

入港・出港時は甲板に人が出てくる時間。苫小牧港入港時も遠く砂浜にわちゃわちゃしているシギチを識別していると甲板に人が集まってきて、入港の様子を撮影したり眺めたりしていた。ちなみにシギチはムナグロとオオソリハシシギだった。識別を終了した辺りで苫小牧港の堤防が現れた。念のため変なカモメが入っていないか観察することにした。

船の動きに身を任せ、双眼鏡には次から次へ新しいカモメが映る。ほとんどがウミネコとオオセグロカモメだったが、急に１羽、真っ黒なカモメが入ってきた。よく見るとミヤコドリだ！東北ではまず見られない鳥で、2023年始に福岡の干潟で見て以来だった。驚いて小さく叫んでしまった...急いで撮影して観察を続けた。こういうことがあるから航路は楽しいよな～となった。

### 2024.09.24　苫小牧→仙台

5:30頃から観察開始。苫仙は2021年3月以来当てていないのであまり期待しないでいた。6:00頃、船尾の方から口笛のような音が聞こえる。凪いでいたとはいえフェリーの駆動音に負けずに船首まで聞こえてくる。相当大きな声で口笛でも吹いているのかしら、と思ったが、上空を１羽のチュウシャクシギが追い越していくのを見て何が起こっていたのかを理解した。

識別出来なかったがヒレアシシギ類が40、コアホウドリ7、クロアシアホウドリ3といった感じ。コアホウは数個体が船の近くを並走してくれた。

## 八戸↔苫小牧（シルバーフェリー）

### 2024.09.23　八戸→苫小牧

シルバープリンセス乗船。ターミナルはなかなかキレイ。9/21に23:59発の苫小牧→八戸に乗ったが、就寝が遅く睡眠時間が取れなかったこと、海況が荒れていたことから、9/22の5:30に起きても半規管がやられてしまい（というか甲板に出られないくらい荒れてた...）、観察を断念。太平洋フェリーが大型でシンメトリーな感じだとすれば、シルバーフェリーは小柄な分、いろいろな部屋が迷路のように敷き詰められていて秘密基地みたいな感覚。甲板には屋根があり5Fと6Fで観察が可能なようだ。雑魚寝部屋を取ったがコインロッカーがあるので安心できる。乗船後は段々と天候が回復し、左舷側（順光）で観察を始めることにした。

出港直後から小さな黒い鳥が波間を縫うように飛んでいた。初見のウミツバメ属だ。コシジロウミツバメが何度も出現したが、想像以上に小さく、素速く、海面すれすれを飛ぶので観察・撮影が難しい。本当に海のツバメという感じで感動。あとはコアホウドリやハジロミズナギドリが飛んだ。普段乗っている太平洋フェリーよりも鳥との距離が近く、とても楽しい。これは鳥屋に大人気なのも分かるなぁと感じた。

12:30頃に船内でお昼休憩を取り、午前中は逆行だった右舷側にでて午後の観察を始めた。音に聞く八苫、三連休なのに鳥屋がいないはずがなく、午前中から右舷側で観察をしていた3名の鳥屋に挨拶して観察を始めた。オオトウゾクカモメは憧れだったので嬉しかった。少ししか観察できなかったので、いつか再チャレンジが必要だ。また、クロハラアジサシが遠くを飛んでいたり、大きなカジキが4度ほど海面にジャンプしたり、船の直ぐ脇でウミネコとマグロの大きな群れが出来ているのを見たりして、本当に楽しかった。

総じて八苫は大満足。もっと早く知っておけば良かったと感じた。

## 竹芝↔八丈島

### 2024.03.21

==noteからの転載==

八丈島に航路で上陸しようとした記録です。素敵なバーテンダー、太平洋君によって船ごとしこたま攪拌されてきました。酔いお手前でした。ネットの海にリリースしておきます。

**乗船までの経緯**

バーダーなら一度は憧れる八丈航路。私もそうでした。季節によって多種多様の海鳥を観察できるそうです。乗船を試みた３月はアホウドリ類のシーズン。一度は絶滅の縁まで追いやられれたアホウドリPhoebastria albatrusは、懸命な保護活動により個体数を回復させています。現在では1,000羽以上のヒナが確認され、メイン繁殖地の伊豆諸島鳥島の個体群は7,000羽を超えたとか（2023年6月　山階鳥研プレスリリース）。

2021年3月中旬に仙台→苫小牧航路に乗船した際は、コアホウドリとクロアシアホウドリが数羽観察できましたが、それ以来、アホウドリ類の観察機会に恵まれませんでした。真っ青な海面を背景にしたコアホウとクロアシのダイナミックソアリングを見て以来、折に触れて「アホウドリ（Short-tailed）見てみてぇ～」という気持ちが鎌首をもたげたりもたげなかったりしていました。自然系の番組でたまに特集されてる求愛ダンスは面白いし、一夫一妻で生涯添い遂げる配偶システムも非常に良い。あと白黒のコントラストがスーパーキレイだしヒナはめちゃくちゃかわいい。属性もりもりバード。

東海汽船でたまにやってるキャンペーンを見つけました。

**「八丈島往復きっぷ　二等和室限定￥12,000/人」**

往復で￥12,000！？お求めやすい…！カレンダーやスケジュール帳と相談して、３月乗船の機会を得ました（元々キツキツ予定だったので、”島流し”リスクは大きかったのですが、無理矢理ねじこみました）。キャンペーンの仕様上、今回は電話で予約を取りました。費用は竹芝到着後、窓口で精算します。予約番号の控えはいつでも参照できるようにしておきましょう。私は大体LINE Keepメモに残しておいています。

絶対アホウドリ見てやるぜ。長谷川博さんの「[アホウドリからオキノタユウへ](https://www.amazon.co.jp/%E3%82%A2%E3%83%9B%E3%82%A6%E3%83%89%E3%83%AA%E3%81%8B%E3%82%89%E3%82%AA%E3%82%AD%E3%83%8E%E3%82%BF%E3%83%A6%E3%82%A6%E3%81%B8-%E9%95%B7%E8%B0%B7%E5%B7%9D-%E5%8D%9A/dp/4406064087)」を読んで予習はバッチリです。クジラさんも見てみたい。あと八丈島でアカコッコとか見たいしサイクリング楽しそう。

## **準備・乗船まで**

八丈島へ海路で渡るには以下の日程で航海を行う大型客船「たちばな丸」に乗船する必要があります。

1.  東京竹芝桟橋　22:30出港

2.  三宅島阿古港　翌5:00到着

3.  御蔵島御蔵島港　6:00到着

4.  八丈島底土港　8:50到着

船内で１泊する必要があります。ただ、22:00乗船開始としても、三宅島到着時に朝5:00強制起床です。鳥屋なら平気かな（平気ではない）。\
太平洋フェリーには何度か乗ったことがあります。心強い準備物君達をデカスーツケースに放り込むことにしました。

-   着替え：それはそう。雨合羽も一応持って行ってます。

-   双眼鏡、カメラ：それはそう２。カメラはビニール袋と輪ゴムで適当にあしらったレインカバーで保護しておく。

-   海鳥ハンド：それはそう３。フェリーで寝る前に読んでニヤニヤできる。

-   酔い止め：乗り物酔いしやすいタイプなので。万全の状態で鳥見ができるようにいつもトラベルミンを使用しています。

-   タオル類：観察器具含め持ち物に潮水かかったりするので。

-   夜ルーティン用のいろいろ：音楽プレーヤーとイヤホン、常備薬、アイマスク。

-   歯磨きセット・風呂セット

-   軽食：観察中も食べられるクラッカーとか。ゴミが出ないようなものだとGOOD

準備が出来たら当日まで待ちましょう。刹那・遠距離観察の多い海鳥ウォッチング（そこが面白いのもある）では、海鳥の予習が大変役立ちます。検索すれば海鳥の動画は結構あります。ありがたく利用させて頂きましょう（飛翔の様子や船からの大きさ・距離など役立ちます。集合知を活用しましょう）。

当日はJR浜松町駅から歩いてフェリーターミナルに向かいました。アクセス性ヨシ！お腹が空いたら近くのビルとかでご飯を食べましょう。私は西京焼きを食べました。最強。なんでこんな美味いんだろう。コンビニとかドラッグストアで、船内で食べるものを用意しておきましょう。

フェリーターミナルの待合には19:50頃に到着。窓口は20:00からオープンしました。手続きを終えて椅子に腰掛けると、周りにもたくさんの人がいることに気付きます。同業者っぽい人、釣り竿みたいなものを持ってる人、めちゃ眠そうにしてる人、寝てる人等々…（中身スカスカでごめんなさい）。それもそのはず、ターミナルには三宅島・御蔵島・八丈島行きの「橘丸」だけでなく、大島・利島・新島・式根島・神津島へ向かう大型客船「さるびあ丸」も就航します。後者の船は22:00には竹芝を出港し、ターミナルで待機していた40%程の人が足取り軽く乗船していきました。

X（旧Twitter（2024年4月4日時点））では、鳥屋の方々は航路探鳥を行うとき、世話になる船を撮影した写真を一言の意気込みと共にポスト（旧ツイート（2024年4月4日時点））します。例に倣ってやっといた。

## **乗船～鳥見まで**

乗船後にすることをまとめてみました。

1.  部屋の確認：\
    今回は二等和室だったので、雑魚寝 on 畳です。寝袋を持参したのでそれに包まりました。

2.  夕食：\
    お腹が空いていると酔いやすいものです。しっかり腹ごなしをしましょう。尚、乗船までに済ませておくのもよいでしょう。

3.  歯磨き：\
    はにがきはお手洗いの洗面台で行いました。

4.  動線確保、下見：\
    甲板の下見です。海面からの高さ、手すりや**屋根**の有無、広さ、部屋からのアクセスを確認します。特に風よけになるアンチの場所を把握しておきたいですね。\
    （いつも航路探鳥をさせて頂いている太平洋フェリーには甲板に屋根がないので、かなり新鮮に感じました…）

5.  夜景・ユリカモメ・レインボーブリッジの観察：\
    東京都の鳥、ユリカモメがレインボーブリッジを超える辺りまで海面に浮かんでいました。底を見通せない漆黒の海面に真っ白なおもちが浮かんでいるようでほっこりしました。流石東京は日本の首都だけあって、クソデカ不夜城の様相を呈しています。ターミナル周辺もArtificial Light At Night(ALAN)がビカビカギンギンに都市生態系に影響しているんだろうな～とか考えてみたり。\
    東京湾を出航するフェリーは、漆黒の夜の中、際立つビカビカレインボーブリッジをくぐります。

いろいろ興奮冷めやらぬですが、時刻は既に22:30を回っています。翌日は八丈島に上陸して一日遊びまくる予定です。鳥見たりお散歩したり放蕩したりする体力をキープしておくためにも、おくすり（酔い止め）飲んで寝ましょう。

## **三宅島就航～**

微睡みの暗闇から、何か人語が聞こえてきました。続いて世界が点灯した雰囲気。まぶたを開けて、船内で一夜を明かしたことを思い出します。時刻は5:00。三宅島への到着を知らせる船長のアナウンスが響いていました。\
着替えて顔を洗って、本土で調達した惣菜パンをもしゃもしゃ食べていたときです。突然の不快感に襲われました。体が覚醒し始めてようやく、太平洋沖の大海流、黒潮に揺られていることを認識したんでしょう…\
酔い止めを光の速さで消化管へぶち込みました。しばらくは耐えられていたのですが、遂にあぁこれはまずいと思いお手洗いへ急行しました。個室を占拠してしまってごめんなさい。Vomitはしませんでしたがずっと苦しかった。あぁ～酔。甲板に出て野鳥観察したかったけど、出来る余裕なんて全くありません。八丈航路に乗船すれば、太平洋沖に元気なザトウクジラのブリーチングが見られると伺っています。私の胃酸の海でもクジラが元気にブリーチングしまくっています。食道を逆流する濁流の奔流には流石に疲弊しました。半規管脱毛したい。

皆も大好きな鳥さんですが、猛禽類などを除き彼らは目が横に付いています。そのため、移動の際は顔をピタッと停止させて周囲の情報を取得するようです。街中のドバト先輩が観察しやすい好例ですが、キジやボソガラスもそう。カワセミやシギチも首をしきりに上下に動かし、顔の角度を頻繁に調整して水面下の餌を探ることをしています（かわいい）。ホバリングするチョウゲンボウなどは、翼を懸命にはためかせながらも、頭はまるで空間に固定したように動きません。私もチョウゲンボウになれば、八丈航路で鳥を楽しむ余裕もできるでしょうね。

御蔵島を過ぎたあたりからようやく楽になってきました。甲板に出てみると既にゴッツい大砲カメラの面々が20名ほど集まっていました。アホウドリ類は秋頃から繁殖を始め、私が乗船した3月には既にヒナが生まれているはずです。親鳥夫婦は懸命に海原を滑翔し餌を集めているでしょう。すなわち、アホウドリ類の観察にはベストシーズン且つ最適な時期なのです。期待もひとしお~~どころか百しおくらい~~あります。

大荒れの海面状況に鑑みて、三宅島の次に寄港する予定だった御蔵島は欠航を決めたようです。御蔵島をそのまま通り過ぎる橘丸。黒潮さんが容赦なく船体を打ち付けるたびにグラつきます。なんで他のバーダーは全く動じないんだ？足が甲板にくっついているのかもしれないなぁと思っていました。

## **就航不可能！**

Ah\~（絶望）\
嫌な予感が的中しました。御蔵島同様、海面状況に鑑みた欠航です。八丈島底土港への寄港を見送り、橘丸は本土の竹芝桟橋へ舵を切ります。アカコッコ…カラスバト…キョン…アシタバ…\
体力の限界、気力もなくなり船室で横になることにしました。あとまた酔ってきて鳥見出来なさそうだったし、ちょっぴり休憩です。

目が覚めたのは7:30。三宅島への再度の寄港を告げるアナウンスが覚醒を促したようです。大分波が落ち着いてきたので、いよいよアホウドリ類ウォッチングの開始です！

右舷も左舷もヒトで埋まっていました。ちょっとの隙間に入れさせてもらい、海面を凪ぐ巨大な影を探します。まず現われたのはコアホウドリ。強面（~~つよおもて~~こわもて）だけどかっこいいね。

その後もコアホウ、コアホウ、コアホウ…と続きます。X（旧Twitter）やブログで予習した限り、八丈航路にコアホウは少ないはずですが、ずっとコアホウが飛んでました。その後、一羽真っ黒なアホウドリ類が飛んでいるのが確認できました。双眼鏡を覗くと\
「アホウドリだ！！」\
ピンクのクチバシと、申し訳程度に残された顔の白色部、コアホウやクロアシに認められる強面さがありません。間違いなくアホウドリです！うっひょ～

かねてよりの憧れの鳥を見られて満足でした。その後も立て続けに飛んでくれて、合計8羽ほど観察できました。黒い幼羽が完全に生え替わるまでは数年かかると言われています。深い蒼を湛えた大海を飛ぶ純白の翼を見た人々が「オキノタユウ（信天翁）」と呼んだのも納得の神々しさです。たまらん

三宅島を過ぎた辺りから、周囲の鳥屋が解散し始めました。ここから竹芝までの海域は渋いのでしょうか。私も空腹＆眠気に耐えかねて甲板を去り、採餌行動を始めました。船内レストラン隣には、レンジでチンだけの簡単なインスタント飯が豊富に取りそろえられた自販機がありました。寒いのでグラタン食べました。

部屋に戻ると、グラタンで取り戻した体熱と早朝の酔いの疲労感で一気に眠りに落ちました。気付いたときには竹芝桟橋に到着しており、急いで荷物をまとめて下船します。ここに私の八丈島上陸計画は未遂に終わったのでした。くっそ～💦アカコッコ、覚えてろよ～💦💦（運賃は全額払い戻されました）

## **バードウォッチングの話**

この日は北風が強かったことから、より北の海域で観察できるイメージのコアホウが多かったと考えられます。あとは天気が良かったためか、八丈航路で観察機会の多い（と聴いている）ウミツバメ類も飛ぶことはありませんでした。鳥の出が悪いときもよく飛んでくれるオオミズナギドリって偉大だな...オオナギくん、いっつも航路で飛んでくれてありがとう。

覚えている範囲で鳥あわせしてみます。\
\
アホウドリ\
コアホウドリ\
クロアシアホウドリ\
オオミズナギドリ\
ウミネコ\
ユリカモメ\
\
以　上　で　す　。

酔いによるグロッキー状態と現場の知識（海域とか）の欠如などで、思ったよりも探すのに苦労しました。今まで行ってきた航路の中で一番渋かったかも。オーストンウミとかいろんなShearwater探したかったという感じ。あわよくばPterodroma属を見てみたかったけど、流石に小笠原まで行かないと見れないですかね。あとヤツガシラの無賃乗船も期待していました（これもXで情報あったです）

種数で言ったらご覧の有様ですが、アホウドリ類が近くて嬉しかったです！じっくり観察するにはいいな～と思いました。一方近すぎて撮影には難儀しました。大きく写せる一方で、ちょっとしたことで画角からはみ出ます。次は視力と飛びものの撮影技術、半規管を鍛えてから乗りたいです。観察道具に飛沫がかかるので、クリーナー、後処理など忘れずに。
