---
title: "九州遠征"
format: 
  revealjs:
    theme: moon
scrollable: true
---

# 概要

-   九州地方で鳥を見てきた
-   2022年12月27日～2023年1月3日

# 01.和白干潟 {background-color="black" background-image="../../static/image/Trip/Kyusyu/Oystercatcher1.JPG"}

## 和白干潟とは？

- 市街地の隣にポンとある干潟。というより河口
- 覇気がないが東アジアフライフェイに登録されている、歴とした中継地

## 和白干潟の鳥

- ヨシガモ
宮城には少ないのでうれしい。

- ミヤコドリ

# 02.志賀島

## 志賀島とは？

- 金印が見つかったとか言われている、福岡県北部の島
- 海ノ中道には水族館があり、ラッコのリロが飼育されていた。

## 志賀島の鳥

- クロサギ
- カツオドリ
- カンムリウミスズメ

## カツオドリについて{background-color="black" background-image="../../static/image/Trip/Kyusyu/Brown_Booby1.JPG"}

志賀島の道路を一周しながら、所々で路駐して（当然一般車の迷惑にならないように駐車する）海を見たがいない。

車を運転しながら岩場の上にヒメウが見られたので、「ならカツオドリも福岡で見られるんじゃね」と話していたら車の横を並走しているのが見えた。草

# 03.今津干潟

夕方過ぎてじっくり観察できなかった。ほとんど寄っただけ

# 04.諫早干拓

## 諫早干拓とは

長崎県東部の諫早湾の地理的な水害を防止するために作られた大干拓。

## 諫早干拓の鳥

- タゲリ
- ヒシクイ
- トモエガモたくさん
- ハイイロチュウヒ

# 05.東よか干潟 {background-color="black" background-image="../../static/image/Trip/Kyusyu/higashiyoka1.JPG"}

## 東よか干潟とは {background-color="black" background-image="../../static/image/Trip/Kyusyu/mutsugoro1.JPG"}
「大授搦」とも呼ばれる、有明湾に面した広大な干潟。シチメンソウが咲く珍しい場所。シギチドリ類の国内最大の渡り中継地・越冬地
我々が行ったときは年末のため、ビジターセンター「ひがさす」が閉まっていた。

## 東よか干潟の鳥
九州っぽい鳥を大部分回収できる

- ダイゼン、ハマシギ、シロチドリ、ソリハシセイタカシギ、アカアシシギetc.
- ズグロカモメ
- クロツラヘラサギ
- ツクシガモ

# 06.荒尾干潟

## 荒尾干潟とは
熊本県の海に面した干潟。水平線に島原天草が見えた。

# 07.出水干拓 {background-color="black" background-image="../../static/image/Trip/Kyusyu/izumi1.JPG"}

## 出水干拓とは {background-color="black" background-image="../../static/image/Trip/Kyusyu/Hooded_Crane1.JPG"}
国内最大級のツル越冬地。タンチョウが有名なので鳥見を始める前は「ツル＝鹿児島」のイメージがなかったが、朝鮮半島を経由してわたってくるマナヅル・ナベヅル類が一万羽ほど越冬する。

早朝にツルの声を聴きながら干拓の区画を周って探鳥するのは地元伊豆沼のガンを探すのに似ていて楽しかった。

## 出水干拓の鳥 {background-color="black" background-image="../../static/image/Trip/Kyusyu/White_naped_Crane1.JPG"}

- ナベヅル
- マナヅル
- クロヅル
- カナダヅル
- ソデグロヅル

# 08.阿蘇山 {background-color="black" background-image="../../static/image/Trip/Kyusyu/aso1.JPG"}

完全に観光

# 09.耶馬渓

完全に観光

# 10.曽根干潟

ズグロカモメ、ツクシガモ