---
title: "津軽半島"
format: html
---

2024年9月8日~10日、津軽半島を周ってみた。

### 9/8　新青森～蟹田

新青森駅で新幹線を下車。駅近くのレンタカー屋さんで車を借り、さっそく北へ向かう。青森県で運転したのはこれが初めてだったかもしれない。大学の海洋実習がこの県であるが、私鉄「青い森鉄道」を利用すれば実習センターへアクセスできるし、気になる施設も青森駅付近にまとまっていた。今回は公共交通機関じゃアクセスしにくいところを攻めていく。

今回の最大の目的地は竜飛崎。秋には津軽海峡を渡るタカが観察できる。毎年9月中旬に、大学のサークルで合宿が行われるが、悉く都合がつかなかった。学生の最後のM2の時期も結局都合がつかなかったので、ならば個人で行ってしまえというわけ。

新青森駅から国道280号を北上する。マップを見ると道路のすぐ横に津軽湾が見えるように感じるが、実際に走ってみると住宅が道路の両側に敷き詰められていたので、窮屈に感じた。数十分ほど車を走らせ、時刻は11:00過ぎ。並行していた津軽線蟹田駅のある外ヶ浜町蟹田のローカルスーパーで本日の夕食、明日の朝食を購入した。この先、いつスーパーが現れるかわからない。

津軽線の路線と別れ、そのまま半島の外周を行き道の駅たいらだてに到着。乗用車が3台停まっている程度だった。おなかがすいたので煮干し醤油ラーメン（￥750）を購入。シンプルでおいしいだしラーメンだった。小さなフードコートにはコインで動くゲーセンの乗り物が並んでいて、壁に設置されたテレビではこの地域の伝承をアニメ化したものが放映されていた。

大体流れとしては
・謎の旅人が民家に「泊めてほしい」と懇願する。

・ずいぶん長いこと居候しているが、金銭をもっていないので、草履に墨汁をつけ紙に足跡をつける。

・足跡がカニになって海に流れ、旅人は「来年からはカニがいっぱい増える」と残して去る。

・実際、カニがたくさん増えて地名が蟹田になった

というもの。伝承・昔話・民謡によくある「横柄な旅人が不思議なお礼をして村が栄える」というもの。教訓を読み取るとするなら「部外者を無下にするな」というところ？

道の駅の裏には海岸防風林があり、陸奥湾を挟んで向こう側には下北半島の山々が見えた。

### 9/8　岬巡り

そのまま進み、午後1:30には高野崎に到着。キャンプ場、出店、灯台、遊歩道と海面に浮かぶ真っ赤なアーチ状の橋。多くの人でにぎわっていたが、正直メチャ暑かった。ここも一応津軽半島を望むことができるため、何かタカがわたっていないかスコープで探してみたが、特にめぼしいものは見られず。

急がないと竜飛崎での観察ができなくなる。ちょっとだけ奥津軽今別の道の駅に寄った後、15:00頃竜飛崎に到着した。駐車場に車を止めてスコープを組み立て観察開始。「風の岬」は穏やかで蝶が舞い、のどかな昼下がりの午後の時間を過ごした...

アレ？全然鳥がわたってない！！呆れるくらい鳥がいない。風が弱すぎて渡るには苦しい日なのか、それとも9月初旬はちょっと早すぎたか？日陰のない岬の先端でジリジリと体を焼かれながら、観光客が入れ代わり立ち代わりボタンを押す石川さゆりsを聴きながら、津軽海峡で舞い続けるオオミズナギドリの白い影だけをスコープで眺めていた。なんなら地元仙台のほうが風強いまであるな。

希望が見えないので、早めに温泉につかって引き上げることにした。その後、階段国道を通って漁港周りを散歩した。夕暮れにもなると気温が下がって過ごしやすかった。

階段国道を登って岬の上に戻ると、水色と茜色が溶け合ったパステルカラーの空に真っ白な雲が浮いていてとても美しかった。雲はゆっくりと形を変えて東へ流れていく。その間にも水色は紺色へと変わっていく。18:00頃、日本海に沈む真っ赤な夕日がとてもきれいだった。太平洋側に住んでいると、海に沈んでいく夕日は見ることがないので、毎回見てしまう。

ポリネシアやハワイなどの島国には星々に関する面白い神話が語られる。ハワイの有名な英雄マウイ（神話における機能としてトリックスターに類型される）は、母ヒナが洗濯物を乾かすために太陽にロープをかけて綱引きをし、太陽の運行速度を遅くした神話が知られる。東にも西にも遮るものがない島々ではそういった神話が芽生えやすかったのかもしれないな、と思った。

ちなみに、トリックスターとしてのマウイはほかにも人間に火を与えた。神話によれば以前まで火を知るのはクイナだけだったが、マウイがその技術を盗んだ挙句、クイナの額に火を押し付けた。ここでは人間が火を獲得した起源と、クイナの額がなぜ禿げている（羽毛がない）のかが語られる。

ところ変わってギリシャではプロメテウスという神が、天界から人々へ火をもたらしたとされる。怒ったゼウス（独り占めしたいのか知らんけどちょっと人間臭い）が、生きながらにしてワシに肝臓をついばまれ続ける責め苦を与えたそう。肝臓の細胞は分化後には細胞周期G0期に移るのだが、何かダメージがあるとG0期を抜け出して間期・分裂期からなる体細胞分裂を続けるらしい。ということで再生してはついばまれを繰り返すプロメテウスさんかわいそう。

火を簒奪して地上界に受け渡す神話は知る限りこれだけ。記紀神話ではイザナミによって生まれたカグツチが生まれつき燃えていたので、陰部を焼かれたイザナミが死んだ話があるが、火が地上にもたらされたことは語られていない。


さて、夜のとばりが下りた竜飛崎は星空がハッキリと観察できた。駐車場には車が2,3台停まっている。少々暑いので窓を開けて夜ご飯を平らげ、リクライニングして早いとこ寝ることにした。

...とはいえ車中泊には慣れていなかったのと車内が思ったより暑く、2時間に1回は目が覚めてしまった...

### 9/9　恐怖の過敏腸鳥見

一応渡りの中継地なので、階段国道の林の中で早朝探鳥としゃれこむ。秋なのでスズメバチ怖い

晴天だった昨晩は案の定鳥を運んでくれたわけではなく、少し新鮮な夏羽のシメがかわいい声で鳴いているだけだった。明け方の岬に立ち、スコープを設置し、タカの渡りの観察準備をする。海峡をコサギの群れがわたっていく。それだけ。

急に下腹部に激痛が襲った。最近来ていなかったので油断していた。持病の腹痛スキルをいかんなく発揮し、駐車場と岬の道を何往復もした。本当に長い道のりだった...腹痛と闘いながらもちらほらと猛禽類のシルエットが北海道から渡ってくる！急いで観察、お手洗いを繰り返した。

観察できたのはオオタカ、ツミ？、ハチクマ、ノスリ、期待していたより種数、個体数ともに寂しく不完全燃焼だった。当時は一眼購入前で、SS設定がバクっているP900で撮影していたので、飛翔を美しく撮影できるはずもなく、ほとんどが証拠写真にすらならない。一方で普段観察する機会がないタカの勇壮な姿を見て、海峡を背景に飛翔する姿を見て、確かに渡りが行われていることを感じた。月並みな感想だが...初めてのタカの渡り観察だったのでしょうがない。

タカ以外も渋く、ニュウナイスズメが岬の電柱でわちゃわちゃしているだけだった。2024年5月に初めてニュウナイスズメを観察していただけだったので観察機会が少ない。やっぱり普段スズメを見ているのでこの配色・模様にはなれないなぁと思ったが、どうやら幼鳥らしい。写真を取ったらキレッキレのマイケルジャクソンポージングをする幼鳥になって面白かった。この小さい体で、生まれてすぐに海を渡ってきたのか...達成感がノリノリのMJポーズをさせたのかもしれない。

## 9/9 竜泊ドライブ＆特天タンチョウ＆土星の観察

小さいころに家族と行ったきりだった竜飛崎を後にして、竜泊ラインを走る。起伏あり、景色よしのいい道路だった。所々に設置された駐車場で休憩し、眼下に広がる蒼い海と碧い森を見下ろしながらほおばるおにぎりが最高だった。まさに「青森」だと感じる。

竜泊ラインを降りるとすぐ、「道の駅こどまり」が見えたので立ち寄ってみた。店内にはカワハギやカレイなどが水槽の中で飼育されていた。餌槍ができるらしい。さらに南下して道の駅十三湖高原へ。写真を振り返っていて気づいたが、外装が牛をモチーフにしている。あまり調べてこなかったが牛の放牧などがされているのだろうか。十三湖と言えばトゥルルなしじみが有名なところといおう印象があった。

小泊・夏泊などはなにやらアイヌ語由来の地名っぽい感じがする。今度ものの本で調べてみようと思った。郷土史には明るくないが、知っていると旅行が楽しくなるだろうと思う。

十三湖から五所川原までひたすらまっすぐに縦貫する、その名も「コメ・米ロード」を南下しつづけた。途中少し左折し、秘境駅として有名な毘沙門駅を見に行った。鉄オタではないと思うが、駅は結構好き。毘沙門って名前がかっこいいよね

その後は鶴田腸の丹頂鶴自然公園に行ってみた。シンプルな自然公園だが、異様なのは湖畔に面したフェンスの中にタンチョウが飼育されていること。ちょっと暑そうだった。立派な鶴の舞橋もあったが、疲れていたので五所川原市街地に戻ることにした。

五所川原で銭湯に入って、明日からの海洋実習のためのご飯を買い込む。なんとロピアに入店した。地元仙台駅にもロピアができたのだが、初めてのロピアは五所川原だ。ショッピングモール内のフードコートででかラーメンを食べて、近隣の道の駅で車中泊をした。ここは広い駐車場に大型トラックや乗用車が計25台ほど停まっていた。

竜飛崎で会った鳥屋から実は今土星が観察できることを教えてもらった。せっかく青森までスコープを持ってきていたので、人通りの少ない駐車場の端っこでスコープを広げ、観察してみることにした。天体観測はあこがれているものの熱心にしたことはない。スマホで方角を確認して探すと、ぼんやり見える恒星の中にカレーパンマンみたいな円盤形の星が見えた。

想像よりもずっと円環が見えてハッピー。アダプターなしの気合スマスコで写真撮影した。この日も早めに寝たが、昨夜とは反対に非常に冷えた。半袖とパーカーだけではしのぎ切れない肌寒さに何度も目を覚ましてしまった...

### 9/10 岩木山

朝4時、気温を見ると15度。そりゃ寒いわけだ...寒すぎるのでコンビニでカフェラテと肉まんを購入。予定していた岩木山ドライブに出発。

薄明りの中、鶴田から望む岩木山はとても美しかった。良すぎて路駐して何枚か写真を撮った。全貌が一目で見れる山が地元にはないのでわくわくである。岩木山に近づくにつれてリンゴ畑が増えてきた。道路のいたるところに落下したリンゴが転がっている。圧倒的なリンゴの物量だ。リンゴ大好きなのでうれしい。

岩木山神社を訪れた。時刻は5:30。地元の方が一人散歩している以外に人はいなかった。境内の中は広々としていて、暑さ続きだった9月頭、冷ややかな落ち着いた空気の中で参拝できた。

山、というくらいなので面白い鳥（ヤマドリ、オシドリ、ヤマセミ、カワガラスなど）が観察できないか期待したが、鳥は少なかった。初めて訪れた場所でもあったので十分に開拓できなかったのもある。ニホンザルには会った。温泉もいろいろあるみたいだが、こんな平日の早朝からやっているところはなく、寒さに震えながら青森市へと戻った。