project: 
  type: website

website: 
  title: "Top"
  theme: morph
  mainfont: sans-serif;
  fontcolor: black;
  linkcolor: hsla(237deg 74% 33% / 61%);
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - text: "About me"
        href: article/about.qmd
      - section: "Bird"
        contents: 
          - article/miyagi.qmd
          - article/trip.qmd
          
format:
  html:
    css: "styles.css"  # 共通のCSSファイル
    toc: true  # 目次を表示
    toc-depth: 2  # 目次の深さ
    number-sections: true  # セクション番号を表示
    