project: 
  type: website
  output-dir: "docs"

website: 
  navbar: 
    tools:
      - icon: twitter
        href: https://x.com/ann0uman
  title: "Top"
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - text: "About me"
        href: https://noumagse.github.io/article/about.html
      - section: "Bird"
        contents: 
          - text: "Miyagi"
            href: https://noumagse.github.io/article/Miyagi.html
          - text: "Trip"
            href: https://noumagse.github.io/article/Trip.html
      - section: "Others"
        contents: 
          - text: "Food"
            href: https://noumagse.github.io/article/others/food.html
          
format:
  html:
    css: "styles.css"  # 共通のCSSファイル
    toc: true
    toc-title: 目次
    toc-location: left
    number-sections: true  # セクション番号を表示
    theme: morph
    mainfont: sans-serif;
    fontcolor: black;
    linkcolor: hsla(237deg 74% 33% / 61%);
    