project: 
  type: website
  output-dir: "docs"

website: 
  title: "Top"
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - text: "About me"
        href: article/about.html
      - section: "Bird"
        contents: 
          - article/miyagi.html
          - article/trip.html
          
format:
  html:
    css: "styles.css"  # 共通のCSSファイル
    toc: true
    toc-title: 目次
    toc-location: left
    number-sections: true  # セクション番号を表示
    theme: morph
    mainfont: sans-serif;
    fontcolor: black;
    linkcolor: hsla(237deg 74% 33% / 61%);
    