project: 
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - "image/"

website: 
  favicon: /static/image/favicon.png
  navbar: 
    logo: static/image/favicon.png
    tools:
      - icon: twitter
        href: https://x.com/ann0uman
  title: "noumaのページ"
  sidebar: 
    style: "floating"
    search: true
    background: "primary"
    foreground: "light"
    contents: 
      - text: "About me"
        href: https://noumagse.github.io/article/about.html
      - section: "Bird"
        contents: 
          - text: "Miyagi"
            href: https://noumagse.github.io/article/list_Miyagi.html
          - text: "Trip"
            href: https://noumagse.github.io/article/list_Trip.html
          - text: "Ferry"
            href: https://noumagse.github.io/article/list_ferry.html
      - section: "Bird List"
        contents: 
          - text: "Bird in Miyagi"
            href: https://noumagse.github.io/article/list_BirdList.html
          - text: "Bird of Ferry"
            href: https://noumagse.github.io/article/list_BirdFerryList.html
      - section: "Others"
        contents: 
          - text: "Food"
            href: https://noumagse.github.io/article/others/Food.html
      - section: "Settings"
        contents: 
          - text: "【工事中】Githubでブログ開設"
            href: https://noumagse.github.io/article/settings/how2thispage.html
          - text: "【工事中】Quartoで記事執筆"
            href: https://noumagse.github.io/article/settings/how2quarto.html
  page-footer: 
    left: "Copyright 2025"

format:
  html:
    css: "styles.css"  # 共通のCSSファイル
    lightbox: true
    theme: 
      light: flatly
      dark: darkly
    toc: true
    toc-title: 目次
    toc-location: left
    number-sections: false  # セクション番号を非表示
    mainfont: sans-serif
    linkcolor: hsla(237deg 74% 33% / 61%)

  revealjs:
    css: "styles.css"
