---
title: "三井商船さんふらわあ（大洗→苫小牧）"
format: html
---

### 2025.03.28　大洗→苫小牧（深夜便）

2025.03.27（木）、上野で見たい展覧会があったので東京に来た。東北でも開催してほしいけど、東北にはデカい美術館やキャパのある会場がなさそうなので仕方がない。上野からただ仙台に帰るのも興がないので、いっそ大洗まで行って、船で帰ろうと思った。

20:00頃、上野駅から常磐線の特急ひたちに乗って一時間ほどで水戸駅に到着。21:20に水戸駅から大洗港フェリーターミナル経由のバスが出ているので、これに揺られて21:50にターミナルに到着。深夜便の出立は翌1:45だが、乗船自体は22:30から可能らしい。誰もいないターミナルで流れていた誰も知らないテレビを眺めていると、あっという間に乗船の時間が来た。

6:30頃起床し、用意していた朝食用のパンを食べ、7:00頃から右舷側で観察を開始した。小雨だったが右舷側の屋根で雨宿りしながら観察。ちょうど金華山沖からだっただろうか、曇りの中、さっそくクロアシアホウドリ・コアホウドリが一羽ずつ飛んだ。またウミスズメもちらほら飛んでいた。さらにアホウドリも少数現れた。アホウドリは背面が茶褐色で眼の周囲だけ白みがかった若鳥や、背面が白い成鳥も見られた。

アホウドリを観察していると、船の後方から中空を飛んでくるハト位の鳥が見えた。今まで見たことのない飛び方の海鳥だと思い、びっくりしながら確認したらまさにキジバトだった。30秒ほど右舷側にくっつきながら飛んでいた。

今回興味深かったのはアホウドリ類が海面に降りていたこと。アホウドリはダイナミックソアリングに適した長い翼をもつが、飛翔時はハクチョウのように助走をつけて飛ぶ。魚食性なので当然なのだが、そんなアホウドリが海面に降りているのはあまり見ない光景だったので、面白かった。

9:00頃、小雨がやみ風もおさまったので、遮るものが少ない左舷側（陸側）に出てみた。トウゾクカモメが現れた。といってもトウゾクカモメ4種は多型が多く（supergeneによってmorphが決定するらしい。ハクガンと同じ）、私が初見したのもつい半年前だったこともあり、現地では識別できなかった。ただ、船の上から飛び方の力強い、海面すれすれを飛ぶでっぷりした鳥をトウゾクだとわかるようになったのは成長だと思う。生殖羽は尾羽が特徴的で識別しやすそうなものだが、見るトウゾクどれもが尾羽が短く、

9:30頃からミツユビカモメの数百羽の規模の群れが見られるようになった。上空を乱舞する群れの中で一羽だけ、大きくて真っ黒な個体がいた。トウゾクカモメが襲っている様子だった。また、11時方向からトウゾクカモメが3羽まとまって出現し、興奮してピントが甘くなってしまった。トウゾクも群れることがあるのか。数羽で襲撃したほうが成功しやすいのかもしれない。

11:30頃、船内に戻って昼食を食べていた。鳥の出が少なくなったこともあり、朝飯が早かったこともある。窓際に座って船内の温かいお茶を飲んでいると、窓の外側を巨大な鳥の群れが流れていった。一服モードから鳥見モードに切り替え、すぐカメラを向けて証拠写真を撮る。見るとアホウドリの成幼入り混じった13羽の群れが海面に浮いていた。これはさすがに悔しすぎる。この航路でアホウドリの10羽を超える群れを見るのは、後にも先にもこれが最初で最後だった。

急いでデッキに戻った。風が強くなってきたので、右舷側での観察にする。同じように船から離れていくウミスズメ類をさばいていると、その中にハシブトウミガラスが入った。12:30頃にはウトウもトビ始めた。

13:00、同じように海面から飛び出した小鳥を見ると、ウミスズメより明らかに大型。よく見るとオナガガモ8羽の群れだった。海を渡って北へ向かうのだろうか。冬場は公園や沼でころころしているかわいいオナガガモの勇敢な一面を見たような気がした。

14:00、トウゾクカモメがたくさん出た。

14;:30　疲れからか酔ってきたので個室に戻り寝た。個室なのがポイント高い。16:00頃、観察を再開。この日は日が出ることはなかったが、それでもこの時間になると分厚い雲に覆われた天蓋の上に上る日も傾いてくる。コアホウドリとクロアシアホウドリを何とか識別し、また粛々とウミスズメ類をさばいていく。そうするとまたカモ軍団が現れた。今度はPintailオンリーではなく、Wigeonも混ざっている。

さらに、津軽海峡沖で海面に褐色の球体と三角形が浮かんでいるのが見えた。よく見るとオットセイの頭と四肢だったようだ。球体には白いひげが生えていて、頭部を海面に出していた。