---
title: "太平洋フェリー（名古屋↔仙台↔苫小牧）"
format: html
---

### 2021.03.11 仙台→苫小牧

初めての仙苫。航路大好き友人に連れられて三人で北海道遠征をすることになった。

仙台からは19:40発になるため、17:00頃にターミナルに到着し、スーパーで買った惣菜などの夜ご飯を2m離れて食べたり、見られそうな鳥や見たい鳥を2m離れて談義するなどして過ごした。コロナパンデミックから1年後だったので、ソーシャルディスタンスしていた。

19:30には乗船を済ませ、翌朝から始まる航路探鳥の舞台である甲板を下見した。冷たい夜風と共に体に付着した潮を落とすため、混雑前に大浴場に入った。太平洋フェリーは大浴場付きなのだ。うれしい

日の出と共に航路探鳥を始めるため寝台に駆け込んだ。同室には一般の方も利用されていたので、目覚ましの音は最小限に控えた。航路探鳥はまだ2回目。どんな鳥と出会えるか、さながらキジバトの求愛ダンスみてーに胸を膨らませながら床に就いた。

翌朝は5:00くらいから観察を始めた。太平洋の波をかき分け征くフェリーの重低音が覚醒の助けになってくれていた。朝のルーティンをしっかりこなして甲板に陣取る。まだ日も出ていなかったように記憶しているが、ミツユビカモメ（学名もtridactyla）がたくさん飛んでいて楽しい。遠くを滑翔するコアホウドリの大きさに驚いたり、船体付近に現れたウミガラスsp.などに発狂したり、今まで航路以外で見る機会がなかった海鳥を見ることが出来て嬉しかった。

左舷で観察すると本州沿岸沿いをハクチョウ・ガンの群れが並走しているのが見えた。更に甲板での観察中、上空をマガンとシジュウカラガンの群れが追い抜いていった。青空を背景にこれからシベリアやカムチャツカに向かうのだろう。航路経験が少なく、海鳥を見るものだと思っていたがこのように渡りを観察できるチャンスでもある事を知った。なるべく船首の方で観察していたがそれでもコンスタントに風が吹き付けるので、手袋貫通して霜焼けになる。太平洋フェリーのあつあつお茶サーバーを利用して休憩しながら苫小牧港まで楽しんだ。

### 2021.03.16 苫小牧→仙台

北海道遠征の最終日。岩手沖からの観察。旅愁に浸る間もないほど海鳥が多かった。3.11の往路では観察できなかったオオミズナギドリ、クロアシアホウドリ、ウトウ、ウミスズメなどのほか、ウミガラスsp.の数も多く楽しめた。

ウトウがめちゃくちゃに多かったが、足島（2020年、コシジロウミツバメのヒナが見つかっている。今まで岩手県三貫島が繁殖南限だと考えられていたが、その記録を更新）での繁殖に向けて集まってきていたのだろうか。

### 2022.08.25　苫小牧→仙台

函館から苫小牧まで一人旅をした帰り。ちなみに函館まではシンプルに新幹線で行った。

オオミズナギドリがめちゃくちゃ飛んだ。水面付近をアカエリヒレアシシギが飛んでいた。あと同世代くらいの鳥屋にあった。めちゃくちゃな虚無だったけど航路自体が好きなのでまぁOKという感じ。トビウオ眺めてた。

### 2023.09.20, 09.21　仙台→名古屋

就活終わって漸く時間が出来たので、シンプル旅行で名古屋に行ってみた。

11:00から汗が止めどなく流れるバス停。働かない頭で座った場所は優先席で居心地が悪かった。領収書を受付の方に見せて乗船→場所取り（とはいえ鳥屋は私一人だったが…）。名古屋行きのフェリーは12:50発なので、苫小牧行きと違って昼前から移動しなければならない。寝室を確認して早速甲板で待機。

ウミネコにかっぱえびせん上げてる人いっぱいいて、たまにオオセグロ幼鳥混ざってた。最初の方は渡りのシギチが数十羽で飛んでいるのが多かったが、14:50を最後に何も飛ばなくなった（海面の波が朧気な輪郭を持った夢想に変わるのに時間はかからなかった）。

16:30からフェリー前方をオオナギが舞い始め、いわき沖でドカンと500+いそうなオオナギ爆弾が遠くの沖に見えた（一直線上になっていたので撮影してみると、その直線から少し離れたところにも30羽ほどまとまっていて、なんだか嘴が大きい。アホウか？）。いわき沖までアカエリヒレアシシギがちょろちょろ出たくらいだったが、いわき沖はオオミズナギドリ、ウミネコの巨大な塊が見えて面白かった。まだ鳥山が見えていたが日も暮れてきたので、その後は日が暮れた17:00過ぎまで探鳥し、17:40に切り上げて今執筆している。

翌日は5:30から観察を開始。静岡県御前崎沖から。三河あたりが鳥の密度が高く、コンスタントにオオミズナギドリやウミネコが飛んでいた。伊良湖崎あたりでタカ見えないかなぁと、頑張って8倍双眼鏡で曇天を凝視したが、トビっぽいシルエットが飛んでいることしか分からなかった。あり得ないくらい高所をクロアシアホウドリが1羽だけ旋回していた。種数は稼げなかったが（時期が微妙すぎる...）、初めて乗った航路だったので楽しめた。

### 2023.09.25　名古屋→仙台

5:30、鴨川沖からスタート。オオミズナギドリたくさん、ウミネコ、オオセグロカモメ、ウミウ、以上。アカエリヒレアシシギも見られなくなって虚無さが増した。相変わらずいわき沖は賑やかだった。16:30の仙台港着時はどっと疲れた。

### 2024.03.30　名古屋→仙台

帰りだけフェリーを利用した。5:30、房総半島沖からスタート。

半年前にも乗っていたが、今回は海鳥が多かった。やっぱり時期の問題が大きそう。

クロガモ、アカエリカイツブリ、カンムリカイツブリ、ハジロカイツブリなどが界面に浮いていた。またアホウドリも成幼合わせて9羽ほど観察できた。クロアシアホウドリやコアホウドリもいた。ヒメウがいたのには驚いた。東北以北のイメージが強いが、関東辺りにもいるのは知らなかった。あとハクセキレイが飛んでいた。仙台着は15:30

### 2024.09.21　仙台→苫小牧

八戸↔苫小牧のフェリーに乗るために、一度苫小牧までフェリーで行くことにした。9月の三連休は、2023年の仙台↔名古屋につづき二度目の航路。

きそフェリーに乗る。平日夜の帰宅ラッシュに巻き込まれ、20分遅延したターミナル行きバスだったが、流石に乗客が多いことと直結バスがこれしかないため、乗船手続き時刻を過ぎていたが何とか乗ることが出来た。

初日はカップラ食べて風呂入って、あと今までスルーしていたラウンジで元劇団四季のVoとピアノ奏者のコンサートを楽しんだ。

・歌詞はタブレット端末で表示していた。

・記録端末が発達してから、CDからWalkmanから、配信サービスまで変化していったが、そもそも音楽とはこのように、決められた時間に生の音楽家が奏でるものを対面で鑑賞する起源があったんだよな

・絵画と同じで、記録端末が出てきてから市民にも門戸が開かれたのかな。気になる一方で市民から発達したポップミュージックとかもありそう。

・新しい歌の発表の場も、今はYouTubeやライブが多いが...

・今まで記録された曲を聴く習慣で生きてきたから、ライブとかである声の裏返りとかアレンジとかが苦手だったんだよね～それってこの歌の正解じゃないよね？って気持ち

・将来は演奏家ではなく、AIによる固定化された音楽が演奏されるようになるのか

5:00前起床、パン食べて観察開始。懸念されていた天気だったが幸い曇り。7:00まで憧れのPterodroma（ハジロナギ）が40羽ほど登場。昨年同時期に仙台↔名古屋を行ったが、海域の違いなのか、仙名航路では見られなかった。Pterodroma属は海鳥ハンドなどで見る限り、他のミズナギドリの中で顔が可愛い感じがする。たぶん瞼がかさになっていて、目元が大きく見えるからだろう。黒白のコントラストがはっきりしていてキャッチーなのもあるかもしれない。吻が寸詰まりで面長な印象がないからかもしれない。曇天の中、一定の頻度の羽ばたきを繰り返しつつも体がブレない飛び方をしており、プロペラのおもちゃみたいだと感じた。オオナギと比べ飛び方に余裕がない。SharwaterとPetrelの違いか？

それからはほとんど虚無だったが、マグロが元気に跳ねていた。海上にウミネコ・オオセが群れていたので、水面の小魚にとっては地獄だろう。

入港・出港時は甲板に人が出てくる時間。苫小牧港入港時も遠く砂浜にわちゃわちゃしているシギチを識別していると甲板に人が集まってきて、入港の様子を撮影したり眺めたりしていた。ちなみにシギチはムナグロとオオソリハシシギだった。識別を終了した辺りで苫小牧港の堤防が現れた。念のため変なカモメが入っていないか観察することにした。

苫小牧港に入港。スマホ弄ってて堤防に気付くのが遅れて慌てて観察開始。船の動きに身を任せ、双眼鏡には次から次へ新しいカモメとウミウが映る。ウミウウミウウミウ、オオセオオセオオセ、ボソボソミヤコ...は？ほとんどがウミネコとオオセグロカモメだったが、急に１羽、真っ黒なカモメが入ってきた。よく見るとミヤコドリだ！東北ではまず見られない鳥で、2023年始に福岡の干潟で見て以来だった。驚いて小さく叫んでしまった...急いで撮影して観察を続けた。こういうことがあるから航路は楽しいよな～となった。


### 2024.09.24　苫小牧→仙台

5:30頃から観察開始。苫仙は2021年3月以来当てていないのであまり期待しないでいた。6:00頃、船尾の方から口笛のような音が聞こえる。凪いでいたとはいえフェリーの駆動音に負けずに船首まで聞こえてくる。相当大きな声で口笛でも吹いているのかしら、と思ったが、上空を１羽のチュウシャクシギが追い越していくのを見て何が起こっていたのかを理解した。

識別出来なかったがヒレアシシギ類が40、コアホウドリ7、クロアシアホウドリ3といった感じ。コアホウは数個体が船の近くを並走してくれた。

### 2025.03.16　苫小牧→仙台

6:00頃から観察開始。2021年3月に乗った苫仙では大量のウトウが海面に浮いていたので、ウトウの群れを期待した。岩手沖からコアホウドリがたくさん出現した。その後、船のすぐそばに別のアホウドリ類が現れた。くちばしの桃色が淡くコアホウドリよりも太く、体全体を覆う羽衣が一様に茶色な鳥だった。

この季節の仙苫は4年前に一度乗ったきりだったが、その時は見ることができないでいた。アホウドリといえば鳥を見る前の自分だったら「南の島の珍しい鳥」という印象だったので、改めてこんなにキレイな鳥が仙台の海で見られることに感動した。

### 2025.03.30 苫小牧→仙台

東京の展覧会を見に行って、そこから仙台まで帰るのに本便を利用した。つまり、東京-（特急ひたち）->大洗-（さんふらわあ　しれとこ）->苫小牧-（-（シルバーティアラ）->八戸-（シルバープリンセス）->苫小牧）-（きそ）->仙台といったItenaryだ。個別に記事を書いている。

苫小牧西港からは前日の19:00に便が出る。29日の夕方17:30からの乗船を前に、ターミナルの待合室は仙台・名古屋に向かう人々でごった返していた。次年度から社会人になり、今後しばらくは航路に乗る時間が取れなくなる。また学生生活最後の航路探鳥だと思うとちょっと感慨深い。いろいろエクスキューズで理論武装できたので、初めてのフェリー内レストランに出陣した。

きそのレストラン「タヒチ」は夕食バイキングを提供している。レストラン前で２北里とちょっとの小銭を券売機に投入して、食券を購入した。太平洋フェリーには10回ほど乗っているが、このバイキングに挑戦するのは初めてだ。航路探鳥より緊張した。

名古屋（みそもつ鍋）・仙台（仙台サーモン）など、寄港地のグルメをいろいろ取り揃えていたようで、すべておいしかった。特にお気に入りだったのはショウガ入りつみれ汁、仙台サーモンのお寿司、ごろごろポテサラ。

ご飯を食べた後、二日連続の航路探鳥の疲れが一気に押し寄せてきた。ターミナルで購入したホワイトエールの網走ビール（著者はホワイトビールが好き）を飲みながらちょっと読書して、22:00前には雑魚寝部屋に戻り寝た。

翌5:00、静かに起床し航路探鳥遠征で蓄えていた菓子パンの残りを平らげ、左舷側に陣取ることにした。5:30。この日は曇りで、普段の苫仙左舷側は逆光になるのだが、この日は日の出を拝むことはできなかった。一応水平線のきわきわにウトウ二羽が飛んで行ったのが見えただけで虚無が続いていた。左舷側は海しか広がっていないので、鳥を見つけても目印がなく再度補足が難しい。このためしばらく様子見した後右舷側に行った。

6:00頃から右舷側を観察し、6:40頃に南三陸沖を通過。ここからウミスズメの小さな群れがぽつぽつと飛び始めた。今回の航路遠征では「へんなウミスズメを探す」を目標にしていたので、ほとんどすべてのパタパタウミスズメを撮影し、マダラやエトウミコウミが入っていないか確かめていった。二日前の大苫では南三陸沖で鳥山は現れなかったのだが、どんどん数が増えていった。

しまいには6:55にウミスズメの34羽の巨大な群れが現れた。学級じゃん。この間はウミスズメ以外のウミスズメ類は現れなかったが、それ以外には一羽の亜成鳥アホウドリが船のすぐそばを通過したり、トウゾクカモメが陸のほうへ飛んで行った（のを写真に撮ったら、海面にウミスズメがパタパタしているのが一緒に映った）など。

7:30、このころからウミスズメのフィーバーが終了し、オオナギがちらほら舞うだけになった。一応トウゾクカモメが一羽飛んだが、それ以外は鳥が少なくなった。ヒートテック＋トレーナー＋もこもこアウター＋雨合羽の四枚重ねではさすがに寒くなり、いったん休憩した。

その後8:00、金華山沖からウトウが現れ始めた。ウトウはウミスズメ類だが、ウミスズメのように５～１５羽程度の群れになって飛ぶことは少なく、多くて３，４羽の群れで飛んでいるので、少し発見が難しい。また、この航路遠征中で初のアビ類が姿を現し始めた。金華山を過ぎ、仙台湾に差し掛かると、船のすぐそばから水面を足で蹴りながら長い翼をバタバタさせて慌てて船から離れていくアビ類がどんどん現れ、22羽ほど見ることができた。ほとんどがシロハム・オオハムだった。

ミツユビカモメをウミネコが複数羽で追いかけているのが目に入った。だいぶもみくちゃしていたので、写真を撮ってみると、ミツユビカモメが小魚を加えていた。どうやらこれを強襲して奪うつもりだったようだ。トウゾクだけでなくウミネコからも襲われるのか

また、船のすぐそばを離れていくアビ類も、よく見ると様々な羽衣がいた。くちばしが生殖羽に見られる黒さを帯び、上面も星をちりばめたような美しいドットが見える一方、頭部の模様は黒褐色で換羽中だったり。チンストラップもベントストラップも、脇の白色部も見えないので、ほとんどすべての識別点を封印した個体。

ほかにはオットセイやイルカなどの海獣も観察できた。非常に良い航路だった！