---
title: "2023.03.19　湖畔公園で散歩"
format: html
date: 2023/3/19
---

前々からみちのく杜の湖畔公園で鳥を見たいと思っていたので出かけた。大きく三つのエリアに分かれており、里山エリア（中央）、南エリア、北（里地）エリアの二つ目、三つ目は駐車料金が取られた（320円ずつ）。里山と里地はトレッキングすれば直通してるのでそれで節約しても良いかも。一年に数回だけ入園無料の日があるが、大変混雑するため鳥なんて見ている状況ではなくなる...

さて、里山エリアはトレッキングのイベントだったらしく人でごった返していた。ラッキーなことにスタッフが団体用の入場券を渡してきて（家に帰ってから気付いた）、個人用より安く入れた。里山エリアは県民の森みたいな感じで山の中に未整備の遊歩道が続く感じ。10:30スタートだったので鳥がいない。エナガとボソブト、カラ類はたくさんいる。

南エリアは東北の古民家が再現されたエリアがある。遠野の古民家ではボランティアスタッフが民話を語り聞かせてくれる。しっかり東北の訛りが入っていて、また臨場感ある語りをしていて聞き入った。「オシラサマ」信仰の起源。若い娘が馬と交際していて、両親が見かねて馬を木につるし皮を剥いだところ、突然舞い上がった馬の皮が、それを見て泣いていた娘を包み込み天上へ飛んでいったそうだ。両親は悲しんだが枕元に娘が現われ、3/14に臼の中に現われる、馬の顔そっくりの虫を裏庭の木に持っていき葉を食べさせるといい、と生前の過ちを詫びると共に伝えた。言われたとおりにすると虫は蚕になった。両親はたいそうお金持ちになったので、夢に現われる「お知らさま」としてまつったそうだ。ゆっくり、しかしはっきり語る昔話を聞いていると、展開の遅さにやきもきしたが、現代は情報をいかに早く入手し吸収していることかを気づかされた。

北エリアには里山エリアに繋がる木道（冠水により通行止めになっていたが）と花木園があったが、そこ以外鳥影が多そうな所はなかった。開場が9:30からなのが勿体ない。北エリアは遊具が少なく（貸し出しはしているそうだが）、鳥が多くて楽しかった。キジバトやモズ、エナガを始め、散歩していると目の前をキジがすたすた歩いて行くのが面白かった。湿性花園は鳥が多く、ベニマシコやシメ、帰りがけにはミヤホのペアを観察できて嬉しかった。
