---
title: "2023.06.10　サシバなどチャレンジ"
format: html
date: 2023/6/10
---

同期に以前から「"アレ"見たい」と言われていたので、山行けと言っていたのだが、実現してしまった。

6/10、バイトが20:00に終わり、自転車を最寄り駅において同期宅に向かった。同期が21:00にレンタカーを受け取りに行ったので、同期の家の近くに着いてからはしばらく夜の見慣れない街を散歩したりした。シャワーを借りてベッドを借りて、いろいろお世話になった。夜ご飯は鳥肉とトマト缶を頂いた。味噌汁（だし入り味噌スプーン大盛一杯＋お湯＋乾燥具）が凄く美味かった。夜ご飯中、同期の別サークルでの活動を色々と聞いた。00:00に就寝。

6/11。2:30に起床。すぐに後輩たちを拾い同期の運転で県北へ向かった。彼も大概ヤバい遠征を繰り返しているので、運転は上手だ。

4:30。駐車場には一台の車が止まっていた。外に出るとホトトギスやエンベリ、カラ類がひっきりなしに鳴いている。霧が出ているものの雨は降っていなかった。しばらく駐車場で朝ご飯を食べていると、"アレ"の鳴き声が聞こえた。鳴き声はガスった上空を西の方へ向かっていき、それに追随するように止まっていた車も向かっていった（ので、おそらく鳥おば）。

朝食を食べた後小雨が降ってきたので、上だけカッパを着て湿原の散策を始めた。鳥がひたすら鳴いているのに、有効視界が非常に狭く、太陽も出ていないので観察がしにくかった。辛うじてアオジとノジコをそれぞれ一羽、皆で見て、あとはひたすら虚無だった。しかし、さえずりは充実しており、アオバトやトラツグミさえ聞こえてきた。"アレ"は出なかった。

その後は湿原の離れで、ツクツクボウシの鳴き真似をするキビタキの声を聴き、ふもとの公園へ向かった。ゆるキャラ看板が突っ込みどころ満載で面白かった。

公園には8:00頃着いた。滝の麓まで降りていき下流側を見ると、キセキレイが数羽虫を加えて食べるでもなくうろうろしていた。しばらく観察していると、凄いスピードでカワガラスが上流から飛んできた。4羽ほどいたらしく、そのうち一羽が5m程先の中州の岩に止まってくれた。未だかつてこんな好条件でカワガラスを観察できたことはない。この機会にたくさん写真を撮ろうとしたところ、カワガラスが来てからほんの1分後、対岸（右側）の笹藪から大きなシルエットがのそっと登場した。

曇天を反射して鈍色に輝く水面と草本の淡い緑色の世界に現われた、漆黒の巨体。ある種の恐怖を覚えるその空間をじっと見据えること、数秒、脳が解を導いた瞬間に後輩が叫んだのを覚えている。野生のクマは浅瀬の川を数往復して、うちらが観察していたカワガラスを吹っ飛ばした後、下流へとずんずん歩いて行った。クマの姿を生で見たことはなかったが、剥製などで見るよりも小柄なことから、ツキノワグマの子どもだと判断した。こちらには気づいていない様子だったので、安全な橋の上へへ逃げた。橋から観察を始めると、そこにはクマとカワガラスの姿はなかった。心臓が興奮と少しの恐怖で鳴り止まぬ中、車に乗り込んで公園を離れた。

ダムはこれといった鳥がいるわけではなく、ダム公園までのオフロードにヤマドリが出る（くらい文明的な道ではない）こと、山間のダムなのでクマタカやサシバなどが見られるかもしれないこと、サシバは夏鳥で電柱に止まってるんだけど見てみたいね、などと話した数秒後、運転席から望むフロントガラスの右上方に、電柱に一羽の茶色いタカが止まっているのが見えた。

ある種確信を抱いていたかもしれない。皆に許可を取りUターン、戻ってみるがどこにも止まっていない。見間違いか？いやまさかと逡巡し更にUターンすると、後輩が窓の外で猛禽を見たと言った。丁度路駐に適した場所だったので急いで車から降りて見てみると、茶褐色の大きな翼が飛んでいる！しかも2羽！皆喜んでいたが、私も死ぬほど嬉しかった！！

3分後、二羽とも別方向へ飛んでいってしまったし、曇天でSSを下げていたため、ブレブレの写真になってしまった。しかしスコープで覗いたサシバの金色の瞳は本当に美しかった。ダムは工事中で通れないのが残念だったが、まだ10:00だったため、更なるカワガラスとヤマセミを求めて、近場の川を上流していくことになった。

11:50頃、道の駅に到着。腹も減っていたのでレストランでそば団子定食を食べた。ツバメの巣が軒先に3つ4つほどあって、成長したツバメの雛がみっちみちになって押し合い合戦をしていたのが本当に可愛かった。

13:00頃、国道の途中途中で降りて川にアクセスし、ヤマセミを探したが全くいない。魚すらいなさそうなので、上流過ぎるのも考え物だ。ただ、宮城のほかのバーダーのブログを見ると、更に上流のポイントなどでヤマセミが見られていたから、ホント分からないものだ。滝を見学するために、獣道をひたすら歩いた。帰り道はゴジュウカラが巨木の樹冠でうろうろしていた（面白い鳴き声は聞こえなかった）。大地は緑のシダに覆われ、その中に朽ちた大木が鎮座し、樹幹を覆う大木から降りる木漏れ日が幻想的な雰囲気を醸していた。霧が出ていたらなお良かったかもしれない。

滝ではカワガラスがジャンプしながら滝登りをしていて、皆で応援した。さきほどクマのポイントでは下流へずびゅーんと飛んでいっていたが、上流へ登るときはこうなるのだろうか（笑）

滝の見学後、渓谷でも探したが、全くいない。諦めて蕪栗沼へ向かった。到着は17:00。沼には数種のカモに混ざって、「アイサのような鋭い嘴、白黒の喉と下尾筒」という、ヘンなカモが二羽浮いていた。その場では全く分からず「ヨシ×オナガじゃね！」と大失言。家で調べたらただのヨシガモだった…。