---
title: "2025.05.23　久々の森"
format: html
date: 2025/5/23
---


就職して勤務続きだったが、今日はGWに働いた分の振休を使って休むことにした。サンコウチョウでも探しに行こうかと考えていたが、急に"アレ"が見たくなって探しに行った。この鳥はまったく経験がないので、あらかじめTwitterなどで情報を探した。すでに初認している地域はあるようだったので、試しに行ってみた。夏の山は久しぶりだ。埃をかぶったスズをバッグにつけて出発。

サークルで行ったときは朝5:00には湿原に到着していたが、今日はゆっくり寝たのでついたのが9:30頃になった。平日の通勤ラッシュに巻き込まれたのもある。駐車場を降りるとホトトギスの元気なさえずりが聞こえてくる。そしてときおりサンショウクイのヒリヒリしたさえずりが上空から降ってくる。大学時代はよくこの二種の声を聴いていたが、就職してからは山に行く機会が減って、久々に聞くことができた。

夏の山、森はあまり経験がない。葉が茂っていて観察しにくいし、ハチやアブがあまり得意ではないのもある。今回もメマトイに苦慮しながら体力を使って湿原を一周した。逆光の中、コサメビタキとノジコが林冠を行き来していた。キビタキ・クロツグミの声はするが姿は見えない。あまりにも舐めた時間に山の鳥を見に来てしまったものだ。

遠くでカッコウとツツドリが鳴いた。カッコウは近所でも見られるが、このような山の中で聞くのは斬新な感じ。アオバトも期待できるフィールドだが、今回はなし。大きなスズメバチを見るたび冷や汗をかいたが、クマとの遭遇もなく一周フィニッシュ。湿原の奥の方に行ってみることにした。

奥では山菜取りの人が何人かいたが、やっぱりバードウォッチャーは私だけ。このフィールドは遊歩道の案内看板以外に人跡を感じさせるものが少ないのでちょっぴり心細い。しかし、今度は駐車場に隣接した木立の中からキビタキとホトトギスを見つけることができ、写真に収めることもできた。特にホトトギスは10mもないくらいの枝にとまって鳴いているのを観察できて満足！またこんなに至近距離によらせてもらえることも少なかったので、その声の大きさに驚いた。

しかし撮影した写真を見て落胆。SS大きめ、ISO小さめにしていたので映ったホトトギスは真っ暗。その後も何度かホトトギスの鳴き声に肉薄する機会があったが、残念ながらもう一度姿を見ることはかなわなかった。次こそは...

また、ホトトギスを探しているとき、背後の枝から「キッ」とか細く聞こえていた。なんだろう？と振り返って音のほうを探すと、なんとイカルが枝の上で採餌をしていた。この季節に見るのは初めてで驚いたが、そういえばこの鳥も漂鳥だ。北海道で夏にシメを見ていたのを思い出した。

"アレ"は結局鳴き声すら聞かせてくれなかったが、大体渡来する時期を見極められた気がする。また、ホトトギス、ノジコにキビタキ、さえずりだけだがクロツグミやトケンを堪能できて、面白かった。次はもっと朝早くに起きて"アレ"を探しに行こう！

帰りに道路で子ぎつねが寝ていたのがとんでもなくかわいらしかった。
