---
title: "2026.01.03 網地島"
format: html
date: 2026/1/3
---

### 2026.01.03 網地島

もはや毎年恒例となった、1/3の網地島探鳥。この日は「一日で観察できた鳥の種数の多さを競う」ビッグデイと被っているが、そちらは応援しながら自分のスタイルで鳥を見ることにしている。

今回は初めて、自宅から石巻の網地島ラインの門脇船着き場までマイカーで赴いた。往路の船は、一応の目的だったウミスズメの群れが遠くに飛んでいるのが見えた。また、門脇出港後、旧北上川河口にコクガンが群れで休息しているのが見えた。昨年の網地島探鳥で、復路の船でコクガンが飛んでいるのが見えたが、もしかすると彼らのねぐらの裏付けが取れたのかもしれない。

毎年、長渡（ふたわたし）から網地を縦貫する網地島線（214号）を踏破する。今回は10:00に長渡で下船し、最初に渡波滅生崎に向かった。毎年、ヒヨドリとメジロが多くみられる場所だが、この日は崖下の岩場にヒヨドリが数十羽の群れで行動していたのが驚いた。まるで春秋の渡りの途中のような規模だった。

灯台のふもとから沖合を覗くが、興味深い海鳥などは見当たらなかった。崖下の青い海の中に細長いシルエットのカモが浮かんでいて、見るとウミアイサだった。オスがメスを取り囲み、首を一直線に伸ばして体をかがめる求愛をしているのが面白かった。

網地島線を網地方面へ歩いていると、急に上空をシロカモメが飛んだ。あまりに突然で撮影はできなかったが、上面が白くミラーとのコントラストもなかったため、シロで間違いないと思う。その後この個体をロストしてしまい、非常に残念だった。

網地島は宮城県本土のほかのフィールドとは異なり、常緑の木々が多く立ち並ぶ。このため冬なのに落葉せず、鳥の影が見えづらい。網地島線では謎のAccipiter属が飛んだり、シロハラがうるさく鳴いていたりしたが、それぞれの姿を補足することができなかった。

毎年よく見られるウソ、ホオジロやカシラダカ、アオジ、カラ類混群（シジュウカラ、ヤマガラ、ヒガラ、コゲラ）を見ながら、ゆっくり網地港へ歩いて行った。弊学の野鳥の会は以前まで網地島探鳥を定期的に開催していたようで、[過去のブログ](http://tohokunotori2.blog.fc2.com/blog-entry-65.html)を見ると名も顔も知らぬ（多分）先輩が「キクイタダキを見た」と書いていた。今回、網地島５回目（多分）にしてようやく、島内でキクイタダキを見ることができた。

キクイタダキ自体、そもそも見るのが久しぶりすぎて、その小ささに驚いた。なかなかサボっていて普段観察しない鳥。でもよく見ると表情のように見える口元や大きな目が面白い。

14:00、網地の港に出ると、見覚えのある大きな鳥が一羽だけ浮いていた。なんとコクガンだ。首の白いリングがあるので成鳥なのだろうが、なぜここに？観察中、尾脂腺ぬりぬりしたり船着き場の海藻を食んだりしていて、特に怪我をしている様子でもなかった。

門脇へ戻る復路の船が網地へ寄港するまであと１時間ほどある。５年前、初めて網地島で探鳥した際にオオワシを見つけたポイントへ行ってみた。腹に穴が開いた食べかけのフグが道路に落ちていた。ポイントは風が強く、とてもじゃないがじっくりバードウォッチングできる環境ではなかったので、すぐに引き返した。一応上空を眺めたが猛禽はまたもやAccipiter属っぽいのが一羽、すぐに山の稜線の下へ隠れてしまったが、飛んでいるだけだった。

久々の網地島踏破で疲れが出たのか、復路はなあなあになってしまった。一応ウミスズメはいました。
