---
title: "Shorebirds, Gulls, Auks etc."
format: revealjs
scrollable: true
---

# Charadriiformes

シギチ、カモメ、アジサシ、トウゾクカモメ、ウミスズメ類などを含む広範なグループ

## Shorebirds in Miyagi
-   セイタカシギ
-   ソリハシセイタカシギ
-   タゲリ
-   ケリ
-   ムナグロ
-   ダイゼン
-   ハジロコチドリ
-   イカルチドリ
-   コチドリ
-   シロチドリ
-   メダイチドリ
-   チュウシャクシギ
-   コシャクシギ
-   ホウロクシギ
-   ダイシャクシギ
-   オオソリハシシギ
-   キョウジョシギ
-   オバシギ
-   コオバシギ
-   エリマキシギ
-   キリアイ
-   ウズラシギ
-   オジロトウネン
-   ヒバリシギ
-   トウネン
-   ミユビシギ
-   ハマシギ
-   ヨーロッパトウネン
-   オオハシシギ
-   タシギ
-   ソリハシシギ
-   アカエリヒレアシシギ
-   イソシギ
-   クサシギ
-   キアシシギ
-   アカアシシギ
-   コアオアシシギ
-   タカブシギ
-   ツルシギ
-   アオアシシギ

## セイタカシギ Black-winged Stilt
-   Stilt = 「竹馬」。ハマシギはStintなので、lをnにタイポすると途端に足が短くなる。
-   Himans（革紐）+pous（足）
-   例年渡りの時期に見られる。近年は個体数が多く、珍しい感じはしなくなってきている。宮城でも繁殖が確認されたりするのだろうか

## ソリハシセイタカシギ Pied Avocet
-   数年に一度くらいの頻度で湿地や海岸に現れている。
-   現れるのは渡り後期（11月とか）や冬が多い印象（12月、1月）。冬に現れる個体は謎すぎる

## タゲリ Northern Lapwing
-   毎冬数羽～数十羽で見られる。

## ケリ Grey-headed Lapwing
-   繁殖個体は少ない。

## ムナグロ Golden Plover
-   学名のfluvaも「黄金色」
-   春秋の渡り時期に沼や湿地で見られる

## ダイゼン Grey Plover
-   ムナグロよりも大きく、灰色味が強い
-   春の渡り時期に一度だけ見たことがあるが、探せばいると思う。

## ハジロコチドリ Ringed Plover
-   夏羽は白い眉斑が目立つ。また、嘴基部は黄色く先端が黒いので識別が容易
-   、という識別点を知らずに一度だけ見逃したことがある。家に帰ってからイカルチだと思って撮ったのがハジコチだと知って絶望した

## イカルチドリ Long-billed Plover
-   コチドリに似ているが、一回り大きくアイリングが目立たない。冬によく見られる

## コチドリ Little Ringed Plover
-   渡りの季節に沼や海岸で見られる。
-   腹を膨らませてビュイッと鳴きながら縄張り争いしているのがよく見られる。威嚇最中は羽毛が膨らんでモフモフに見える。

## シロチドリ Kentish Plover
-   周年海岸に生息。

## メダイチドリ
-   渡りの時期に見られる。目が大きく見えるので「目大」。
-   橙色の羽衣なのでメ「ダイ」だと思ってた。

## チュウシャクシギ

## コシャクシギ
2022年は当たり年で、たまたま観察できた。

## ホウロクシギ
数は少ない。

## ダイシャクシギ
数は少ない。飛翔時、翼下面と腰が白い

## オオソリハシシギ

## キョウジョシギ

## オバシギ
数は少ない印象。数度しか見たことない

## コオバシギ
2021年春に一度だけ

## エリマキシギ
毎年秋に多い。

## キリアイ
ほとんど見ない

## ウズラシギ
あんまり多くない

## オジロトウネン
数は少ない。

## ヒバリシギ
ほとんど見ないが探せばいそう

## トウネン
2024年秋は大当たりだった。普段は数十羽見られれば上々の場所で150以上の群れが見られた

## ミユビシギ
海岸や河口で越冬している。波打ち際でシャトルランしてる

## ハマシギ
海岸や河口で越冬している。春になるとお腹が黒くなるので、羽衣の変化を楽しめる

## ヨーロッパトウネン
少ない

## オオハシシギ
数羽だけ県内の沼に越冬しに来る

## タシギ
越冬してるし渡りの時期も見られる。田んぼの用水路とか

## ソリハシシギ
渡り時期によく見られる

## アカエリヒレアシシギ
いまはなき県内のポイントで一度だけ見ている。

## イソシギ
留鳥。尾羽ビコビコで楽しい

## クサシギ
11月とか遅い時期に、あまりシギチのいなさそうな場所で見る。謎

## キアシシギ
渡り時期にめちゃ多い

## アカアシシギ
渡り時期に数羽ほどちょろちょろ見られる。ツルシギに似るが、嘴は上も下も赤い。飛翔時の風切りの白色部が目立つ。

## コアオアシシギ
渡り時期によく見られる。アオアシシギより体型が痩せてる印象で、たまにセイタカシギと見間違うことがある。嘴はまっすぐ

## タカブシギ
渡り時期にちょろちょろ見られる

## ツルシギ
渡り時期に見られるが、秋の非生殖羽が多い。アカアシに似るが、上側嘴は黒い。飛翔時、風切りは白くない

## アオアシシギ
渡り時期によく見られる。コアオアシよりも嘴が反っていて、体型が気持ち太く感じる

# Gulls and Terns in Miyagi
-   ミツユビカモメ
-   ユリカモメ
-   ウミネコ
-   カモメ
-   ワシカモメ
-   セグロカモメ
-   オオセグロカモメ
-   コアジサシ
-   クロハラアジサシ

## ミツユビカモメ
冬の網地島フェリー

## ユリカモメ
冬、公園や下流の河川で見られる。幼鳥は嘴がオレンジ色

## ウミネコ
留鳥。

## カモメ Mew Gull
冬鳥。数は多くない
日本人は猫っぽいカモメと言われれば「ウミネコ」だが、海外の人は「Mew Gull（＝カモメ）」だと感じたのだろう。Mewは猫の鳴き声

## ワシカモメ
冬鳥。数は多くない

## セグロカモメ
数は少ない

## オオセグロカモメ
留鳥。ウミネコに並んで多い

## コアジサシ
夏鳥。

## クロハラアジサシ
梅雨の時期に沼地で見られる。秋にも見られることがあるらしい。

# Skuas and Jaegers in Miyagi
-   トウゾクカモメ

## トウゾクカモメ

# Auks and Murres in Miyagi
-   マダラウミスズメ
-   ウミスズメ
-   ウトウ

## マダラウミスズメ
仙台湾で越冬している（？）生態が謎

## ウミスズメ
冬の網地島フェリーで見たい

## ウトウ
冬の網地島フェリーで見たい

# 宮城で観察されたことのあるチドリ目
-   ミヤコドリ
-   オオメダイチドリ
-   レンカク
-   オグロシギ
-   サルハマシギ
-   アメリカウズラシギ
-   オオジシギ
-   メリケンキアシシギ
-   ツバメチドリ
-   ズグロカモメ
-   シロカモメ
-   ハジロクロハラアジサシ
-   ケイマフリ