---
title: "Songbirds"
format: revealjs
scrollable: true
---

# Passeriformes
スズメ目。地球上に6,000種以上の種が知られている最も大きな分類群。

# Songbirds in Miyagi
-   サンショウクイ
-   サンコウチョウ
-   オオカラモズ
-   モズ
-   カケス
-   オナガ
-   コクマルガラス
-   ミヤマガラス
-   ハシボソガラス
-   ハシブトガラス
-   キレンジャク
-   ヒレンジャク
-   ヒガラ
-   ヤマガラ
-   コガラ
-   シジュウカラ
-   ヒバリ
-   ヒヨドリ
-   ショウドウツバメ
-   ツバメ
-   イワツバメ
-   ウグイス
-   ヤブサメ
-   エナガ
-   センダイムシクイ
-   オオヨシキリ
-   オオセッカ
-   セッカ
-   メジロ
-   キクイタダキ
-   ミソサザイ
-   ゴジュウカラ
-   キバシリ
-   ムクドリ
-   コムクドリ
-   ホシムクドリ
-   ヤドリギツグミ
-   クロツグミ
-   マミチャジナイ
-   シロハラ
-   アカハラ
-   ツグミ
-   ハチジョウツグミ
-   エゾビタキ
-   コサメビタキ
-   オオルリ
-   ノゴマ
-   キビタキ
-   ルリビタキ
-   ジョウビタキ
-   イソヒヨドリ
-   ノビタキ
-   カワガラス
-   スズメ
-   キセキレイ
-   ハクセキレイ
-   セグロセキレイ
-   ビンズイ
-   タヒバリ
-   アトリ
-   シメ
-   イカル
-   ウソ
-   ハギマシコ
-   ベニマシコ
-   カワラヒワ
-   ベニヒワ
-   イスカ
-   マヒワ
-   ホオジロ
-   ホオアカ
-   カシラダカ
-   ミヤマホオジロ
-   ノジコ
-   アオジ
-   オオジュリン

## サンショウクイ

## サンコウチョウ Japanese Paradise-Flycatcher
陽キャ感あふれる英名。
学名はTerps（官能の）phone（声）+atro（黒い）caudatus（尾）だというが、結構濁音のある声で鳴く。

## モズ
留鳥

## カケス
漂鳥。秋や冬に低地で見られることが多い

## オナガ
東日本なのでこのステキな鳥が分布している

## コクマルガラス
ミヤマガラスの群れに数羽混ざるだけ

## ミヤマガラス
毎冬田んぼなどに来る

## ハシボソガラス
東北大学や花壇自動車学校でくるみを割る行動が観察されている。

## ハシブトガラス
留鳥。

## キレンジャク
年変動大きい。当地では春先に渡り途中で立ち寄る印象

## ヒレンジャク
年変動大きい。当地では春先に渡り途中で立ち寄る印象

## ヒガラ
漂鳥。

## ヤマガラ
留鳥。

## コガラ
漂鳥

## シジュウカラ
留鳥

## ヒバリ
留鳥。冬も平地で伏せてる。

## ヒヨドリ
留鳥

## ショウドウツバメ
ツバメに混じって飛んだり、単独の数十羽の群れで飛んだりしてる。渡り時期に見られる

## ツバメ
夏鳥。

## イワツバメ
夏鳥

## ウグイス
留鳥

## ヤブサメ
夏鳥

## エナガ
留鳥

## センダイムシクイ
夏鳥。渡り時期に公園などで頑張って観察する。
下嘴が一様に明るい橙黄色で、暗色部がないのはセンムシだけらしい。
エゾ・メボソ・オオムシは先端に暗色部。

## オオヨシキリ
夏鳥。川の葦が多く生えている辺りや田んぼで囀ってる。渡ってきたばかりのタイミングでは夜も囀ってるのでうるさい

## オオセッカ
夏鳥（？）。鳴き声を一度だけ聞いたことがある

## セッカ
留鳥。夏によく鳴いているが冬は探しにくくなる。

## メジロ
留鳥。

## キクイタダキ Goldcrest
頭部の菊が黄色に開くところを見たことがない。別種でFirecrestなんてのもいるらしい

## ミソサザイ
留鳥。著者にとって所謂相性の悪い鳥

## ゴジュウカラ
漂鳥。冬は混群に混ざって控えめに「フィフィフィフィ」してるけれど、5月頃山にいくとうるさく「フィフィフィフィ」してる

## キバシリ
留鳥。冬に低地で見かけないので、年中山にいる？

## ムクドリ
留鳥。

## コムクドリ
夏鳥。日本海側と比べると少ない

## ホシムクドリ
冬鳥。2023,24年は同一フィールドで二年連続越冬しにきた

## ヤドリギツグミ
迷鳥。東北大学野鳥の会の毎週の土曜探鳥中に一度だけ発見された。

## クロツグミ
夏鳥

## マミチャジナイ
2022年に越冬していた。

## シロハラ
たぶん冬鳥

## アカハラ
冬鳥の場所もあれば夏鳥の場所もあるような印象

## ツグミ
冬鳥。2024年冬は全く見られてない

## ハチジョウツグミ
毎年数羽見られる。見に行ってない

## エゾビタキ
数は少ないが秋に多い

## コサメビタキ
夏鳥。

## オオルリ
夏鳥

## ノゴマ
渡りの時期に気合いで探すことがのとりで流行っている

## キビタキ
夏鳥。水仙の学名

## ルリビタキ
漂鳥。

## ジョウビタキ
冬鳥。安心の尾羽ビコビコ

## イソヒヨドリ
留鳥。Urban bird

## ノビタキ
渡りの時期に通過。宮城に繁殖できる高地はあるのだろうか？

## カワガラス
留鳥。尾羽ビコビコなので、観察していると楽しい

## スズメ
留鳥

## キセキレイ
漂鳥？Grey Wagtailなのだが、じゃあYellow Wagtailは誰なんですかというとツメナガセキレイらしい

## ハクセキレイ
留鳥。尾羽ビコビコだが、たまに尾羽がちょん切れてる個体にあう

## セグロセキレイ
留鳥

## ビンズイ
漂鳥？眉斑が後部で二つに区切れていることで識別してる

## タヒバリ
漂鳥？

## アトリ
冬鳥

## シメ
冬鳥。あくタイプって感じの外見だが声がかわいらしい

## イカル
漂鳥。相性悪い鳥その２

## ウソ
漂鳥。足が短くて可愛い

## ハギマシコ
冬鳥。

## ベニマシコ
冬鳥。渡去してしまうので、北海道みたいな完熟ベニマシコには会えない
猿の顔みたいな色なので猿子

## カワラヒワ
留鳥。さえずりが迫真で面白い

## イスカ
冬鳥。2024年1月に山に見に行った一回きり

## マヒワ
冬鳥。

## ホオジロ
留鳥

## ホオアカ
留鳥。いるところに行けばしっかりいる

## カシラダカ
冬鳥。

## ミヤマホオジロ
冬鳥。局地的らしいので、見つけると嬉しい

## ノジコ
夏鳥。ミヤホより局地的なので、見つけると嬉しい

## アオジ
留鳥。よくさえずってる

## オオジュリン
留鳥？5月に一度だけ見つけたことがあるが、それ以外は冬

# 宮城で観察されたことのあるスズメ目
-   オウチュウ
-   ホシガラス
-   コヨシキリ
-   トラツグミ
-   コルリ
-   ムギマキ
-   ニシオジロビタキ
-   イワヒバリ
-   カヤクグリ
-   キガシラセキレイ
-   オオマシコ
-   ツメナガホオジロ
-   コホオアカ
-   クロジ
-   シベリアジュリン
-   コジュリン