---
title: "2023.6.29　かっこいいクロハラアジサシ"
format: html
date: 2023/6/29
description: "かっこいいクロアジをライファーした"
---

### 2023.6.29　かっこいいクロハラアジサシ

毎日家で就活の準備＆研究計画練り練り＆大学院の講義レポート打ち倒しに気が滅入ってきた。「今年試験が受からなければ来年もこんな無為な生活を送るのだろうか。」「お昼ご飯大学で済ましたいけど（安いので）。」「研究手法決まらないなぁ」とか色々考えてしまって精神衛生上よろしくない。かといって朝から探鳥に行くのも罪悪感がすごいという、面倒な精神構造をしている。罪悪感が少なく、帰宅後の作業の効率を考えて、いつものように午後から出かけた。

午後14:30、増水したMF川で越夏中のオオハクフレンズはしっかりやっているだろうかと見に行くと、三羽いた。内一羽は口を開けたりしていて、暑そうだった。午後15:30、アマサギを探しながら（いなかった）ようやく沼に到着。眼前に広がる面長な入道雲が夏の香りを教えてくれる。大学院に進学してから、何もできずにこの季節がやってきた。また鬱々とする心を持て余しつつペダルをゆっくり漕いでいると、その白く広大な雲の中を、どこまでも自由に舞う翼が見えた。微妙な向かい風に体力を削り取られていたが、出発前に「見れたら良いなぁ（自由聴講）」として一応予習していた沼アジサシがいる！！テンションが最高潮になった。

最初の邂逅はすぐに終わってしまったので、また出てくることを祈り、東側のヨッシー（ヨシゴイ）を探しに行った。これまた直ぐに見つけることが出来、久々にじっくり観察できて嬉しい…と思ったつかの間、ぽつぽつと雨粒が双眼鏡を持つ手を濡らしてきた。直ぐに本降りになり、急いで沼に隣接する公園の屋根付きベンチへ駆け込んで雨宿りをした。雨に打たれる中全力疾走し、沼上空を舞うアジサシが逃げないでくれと焦燥感に身を焦した。

一過性の雨だったようで15分もすれば西から晴れ間がやってきて東側の暗雲に虹を作った。何も考えずに虹に見惚れたのは小学校以来か。だいぶメンタルが弱っていたのかもしれない。雨に濡れたぼさぼさのモズがふるふるしていて可愛かった。雨が止み、急いで沼に駆けつけるとやっぱりまだ飛んでいてくれた。

コアジサシよりもゆっくり飛び、たまにちゃぷんと静かに潜水する。紅色の嘴に黒線の入った顔が妖艶。よく見るとお腹が黒く、なるほどクロハラだなと感じた。ヨシゴイはその後出なかった。

帰りは追い風でサイクリングが楽しいし、潮の香りにしばらくぶりにリフレッシュできた。17:30過ぎだというのに、西日に照らされて松の幼木の上でカッコウ（推し）が一羽さえずっていた。だらんと垂れ下がった翼と、囀るときの尾羽びこびこが好きすぎる。推しに会えたのも良かった。すごく良い鳥見だった。カラシラサギも一応予習していたがまぁそんなに出るものでもない。いい切り替えになった。
