---
title: "県北ガン"
format: html
---

## 伊豆沼・蕪栗沼・県北その他

大好きなガン類の観察記録を中心とした記録。2020年11月の大学サークルの行事でねぐら入りを見たことがきっかけで、鳥の中でガンが一番好きになった。

## 2022.12下旬　伊豆沼・蕪栗沼

早起きして塒立ちを見に行った。この時はまだどこに何がいるのかつかみきれてないので、いろいろぐるぐる田んぼを回った。

田んぼを回る中、交差点付近、道路から一区画目の田んぼにカリガネが群れているのを発見。本来なら道路に隣接した一区画目の田んぼだと警戒されやすいが、対向車線をはさんでいたのでばっちり観察できた。

9時30分過ぎ、ようやくシジュウカラガンを見つけた。マガンの群れの中に三羽ほど混じっていて、畦の上で採餌をしていた。ここで宮城で見られる亜種シジュウカラガンの特徴を少し挙げてみる

-   マガンより一回りほど小さい

-   首の付け根に白い首環がある

今回観察できた個体は以上二つに該当しない。マガンと同大に見えるし、付け根の首環も確認できない。飛来数の多い亜種シジュウカラガンではなく、亜種アラスカシジュウカラガンの可能性がありそうだ。

何より、そもそもその他2個体はシジュウカラガンっぽくもない。一個体目はかなりシジュウカラガンの特徴が出ているが、一般的なシジュウカラガンよりも顔の黒白模様のコントラストが曖昧に見える。幼鳥だとしてもここまでぼやぼやした個体は見たことがない。

さらにもう一個体目を見てみると、同様に顔の黒白模様の曖昧なコントラストに加え、嘴のくすんだピンク色、嘴基部と目の周りの白色部、首の黒の弱さから、シジュウカラガンとマガンの交雑を疑いたくなる個体である。そのシジュウカラガンもおそらくアラスカシジュウカラガンなのだが...曰くありげなファミリーみたいだ。

筆者はこの日以来発見出来ずにいるが、2024年10月のシーズンはTwitter上でも類似した個体の観察が報告されている。同じ個体だと嬉しい。何より当時写真を全く撮っていなかったので、もう少し特徴の分かる写真を撮ってみたい。

10時前、謎のシジュウカラガンと分かれて直ぐに、十数羽のカリガネの群れを見つけた。行動の様子を見ると３家族くらいいそうだ。中には額の白色部がない幼鳥も混ざっていた。よちよち歩きながらしきりに採餌しつつ、数羽同士で首を上下に上げ下げしていた。「ウチの子どもをよろしくお願いします」みたいなご近所付き合いだろうか。

サークルの同期と2021年10月に見つけたカリガネはマガンの群れの中で挙動不審にくねくねしていて、それ以来「くねくねしているならばカリガネである」という命題が屹立している。これも謎のくねくね行動だったのかもしれない。

10:30頃、蕪栗沼に移動した。この日は蕪栗沼ではなく白鳥地区の方にヘラサギが２羽移動していた。白鳥地区内の湿地を見るために歩道をうろうろしていると、突然足下から大きな鳥が飛び立った。ずっと対岸に意識を向けていたため非常に驚いた。空中へ飛び去るゆったりとした飛び方を見つけると、更に驚いた。この沼で越冬しているサンカノゴイだったのだ。他に鳥屋はいなかったが、サンカノゴイには申し訳ないことをした...これからは慎重に覗くことにする。

まだまだ見たりないが、この日は鳥とは関係なく普通の友人を連れていたので、鳥見はここで終わりにして県北を観光することにした。

## 2025.01の県北レポート

年越し後のガンの分布はあまり知らなかったので、このシーズンはガンを集中的に探すことにした。幸い県北に訪れることが多かったので、用事を終えた後にパパッと行うことが出来た。

### 第一週　市街地付近のシジュウカラガン

宮城県の調査によれば、1月のシジュウカラガンは蕪栗沼から化女沼にねぐらを移し、古川市街地よりも西で採餌を行うそうだ。この日は古川から加美のあたりに目星を付け、田んぼを回ってみることにした。

化女沼付近の田んぼに模型みたいにポツンと座っていた一羽のシジュウカラガン以外は、やはり西古川や加美市街地周囲の田んぼで採餌を行っていた。古川から離れてもほとんど雁行が見えなかったので不安だったが、市街地に近づくにつれパラパラと飛び始めた。もしかしてと思い窓を開けると、やはりシジュウカラガンの声だった！

慎重に声が飛んでいった方に向かうと、マガンの群れに数十羽規模で混ざっていた。今まで年を越す前の11月や12月に蕪栗沼周辺で見ることが多かっただけ、この辺りで観察できるのは新鮮に感じた。

### 第二週　ハクチョウ数羽

加美の方まで分布していたと言うことはもっと西にもいるかな～と思い、小野田の方まで行ってみた。結果は積雪がものすごく、ガンが採餌出来ないので数羽のハクチョウしかいなかった...逆に君たちは何故いたの...？積雪が解けた頃にまた行ってみる

キレイなオス成鳥のコチョゲンを見つけたが、防雪柵に乗ったと思うと直ぐ雪景色に消えていった。

### 第三周　伊豆沼ハクガン

ハクガンの分布を調べに行った。ハクガンと言えば伊豆沼をねぐらにしているので、そちらに行ってみる。周囲の田んぼにはオオヒシクイやマガンの群れは見られるけどハクガンの姿はない。試しに伊豆沼北部の若柳や志波姫へ行ってみた。こちらもマガンやヒシクイだけでハクガンは見えない。

意気消沈して伊豆沼に戻ると、北部の一角に10羽の群れが見えた。四方をマガンにガードされているので近づけない。遠くから何とか観察できた。

## 2025.02の県北レポート

一つ大きな仕事が一段落したので（まだのこってるけど）１月よりも時間を使えるようになった。

### 第一週　ハクガン撃沈

一月第三週のようにハクガンを探しに行った。結果は撃沈。何処を探してもいない。

前回のように伊豆沼周辺を探し、今度は更に奥の石越辺りまで。途中若柳で標識オオヒシクイを見つけた。黄色首環で「B41」「B47」「B49」と記されていた。ここら辺は伊豆沼周辺よりもガンが多く、「越冬後期にはねぐら周辺の食べ尽くされた田んぼよりも遠くに散らばる」のは本当だと分かった。だからこそ年明けのガン探しは難しいのだが...

秋田で観察したハクガンはねぐら入りが非常に遅かった。今回もねぐら入りを出待ちしてみたがいつまで経っても現れずタイムアップ。

### 第4週　大当たりのガン見

一月第二週に赴いた加美の方に出かけてみた。一月の時点ではまだまだ雪深く、麓の方の田んぼにハクチョウが数羽入っていただけだった。二月も下旬で、古川や化女沼周辺といった、ねぐら近くの落ちモミは食べ尽くしたのか全く見られなくなった。

加美市街地で気になっていたラーメン屋さんによって昼食をいただいた。注文してから5分ほどで美味しいラーメンがでてきた。あっさりだけどしっかり鳥肉の旨味が染みてる、何度も飲みたくなるような塩スープのチャーシュー麺だった。

車を下野目の方へ走らせると段々と田んぼにガンが降りているのが目立ち始めた。その数は宮崎へ向けてどんどん多くなり、数百羽規模の雁の群れが青空と船形山を背景に飛ぶ様子がコンスタントに見られるようになった。加美でガンを見ることは初めてだったので、非常に印象深かった。田んぼの雪はまだ残っている部分があるものの、雪解けの田んぼに集中して降りているようだ。

降りているガンを見ると、マガン：シジュウカラガン＝5:3くらいの割合。一羽だけマガン×シジュウカラガンの雑種を見つけたり、一羽だけヒシクイを見たりした。ハクガンを探したが見当たらない。渡りのルートが違うので、ここには立ち寄らないのかもしれない。伊豆沼周辺で見るように車を停めると何度か飛ばしてしまった。伊豆沼周辺よりも警戒心が強いように感じた。

面白いのはオナガガモの群れがマガンに混ざって田んぼで採餌していたことだ。オナガガモも北帰行でねぐらを北西に移しているのかもしれない。コハクの中には赤い首輪を付けた個体を二個体見つけたが、交通量が多かったり、マガンが周囲で警戒しまくっていたりしたので、うまく読み取ることが出来なかった。

他に興味深い鳥は見られなかったが、土地勘がないだけで慣れてくれば面白いのが見られるかもしれない。

## 2025.03の県北レポート

1月下旬から始まっていたガンの北帰行がほとんど完了した。まだ周辺田んぼに残っているかは微妙だが、一応行ってみる。

### 第一週　みんなでガン

大学を離れる同期達と野鳥観察をした。この日は田尻・蕪栗沼方面を攻めた。

蕪栗沼のガンはすっからかんでほとんど残っていない。上空を数羽のマガンが鳴きながら、まばらに飛ぶだけ。悲しい。

登米の高速道路（45号線）を運転中、北上川の周辺田んぼに十数羽のガンが降りていた。高速道路だったので助手席の同期がパパッと観察すると、ヒシクイの群れのようだった。